"""Konten Shio — Anjing."""

ANJING_CONTENT = {
    "tagline": "🐕 Shio Anjing",
    "chip": "SHIO",
    "title": "Anjing — Sosok Setia yang Bisa Dipercaya",
    "p1_label": "Siapa Kamu",
    "p1": "Shio Anjing dikenal sebagai simbol kesetiaan, kejujuran, dan rasa keadilan yang kuat. Kamu jarang berkhianat pada orang yang sudah kamu percaya, dan selalu berusaha melindungi orang-orang terdekatmu. Kamu juga peka terhadap ketidakadilan, dan tidak segan membela orang yang menurutmu diperlakukan tidak adil. Kesetiaanmu biasanya teruji justru di masa-masa sulit, saat orang lain mulai menjauh, kamu justru cenderung tetap berada di sisi orang yang kamu sayangi. Dalam lingkungan kerja, rasa tanggung jawab dan keadilanmu membuatmu dipercaya memegang peran yang butuh integritas tinggi. Orang-orang di sekitarmu tahu bahwa kalau kamu sudah berjanji, kamu akan berusaha keras menepatinya, apa pun yang terjadi.",
    "p2_label": "Kekuatan & yang Perlu Dijaga",
    "p2": "Kesetiaan dan rasa keadilanmu membuat orang lain merasa aman menjadikanmu sahabat atau rekan kerja. Kamu juga bisa diandalkan dalam situasi sulit sekalipun. Namun sisi waspada dalam dirimu kadang membuatmu terlalu khawatir atau curiga tentang hal-hal yang belum tentu terjadi, sampai sulit benar-benar merasa tenang. Kecenderungan untuk selalu memikirkan skenario terburuk ini bisa membuatmu kelelahan secara mental, bahkan ketika kenyataannya semuanya baik-baik saja. Kamu juga bisa terlalu keras menilai orang lain yang menurutmu bersikap tidak adil, tanpa memberi mereka kesempatan untuk menjelaskan sudut pandangnya.",
    "quote": "Kewaspadaan itu penting, tapi jangan sampai membuatmu kehilangan ketenangan di masa sekarang.",
    "p3_label": "PR Kecil Buat Kamu",
    "p3": "Ketika muncul kekhawatiran tentang sesuatu yang belum terjadi, coba tanyakan pada diri sendiri seberapa besar kemungkinannya benar-benar terjadi, sebelum membiarkan kekhawatiran itu menguasai pikiranmu. Kamu bisa membuat catatan sederhana berisi kekhawatiran yang pernah muncul, lalu tinjau ulang setelah beberapa waktu untuk melihat berapa banyak yang benar-benar terjadi. Latihan ini bisa membantumu melihat dengan lebih jernih bahwa sebagian besar kekhawatiranmu sebenarnya tidak pernah terwujud.",
    "domains": {
        "karir": "Rasa tanggung jawab dan integritasmu membuatmu jadi sosok yang dipercaya memegang posisi penting, terutama yang berhubungan dengan kepercayaan atau keadilan, seperti HR, legal, atau peran yang mengharuskan kamu membela kepentingan orang lain. Rekan kerja tahu kamu tidak akan mengkhianati kepercayaan yang diberikan. Namun kecenderunganmu terlalu banyak memikirkan skenario terburuk bisa membuatmu ragu mengambil keputusan yang sebenarnya sudah cukup jelas, karena terus mencari kemungkinan yang bisa salah. Kamu juga bisa terlalu keras menilai rekan kerja yang menurutmu bersikap tidak adil, tanpa memberi mereka kesempatan menjelaskan konteksnya. *PR: Ambil satu keputusan kerja yang selama ini kamu tunda karena terlalu banyak mempertimbangkan kemungkinan buruk.*",
        "asmara": "Dalam hubungan, kesetiaanmu tidak diragukan, kamu adalah tipe yang akan tetap ada bahkan di masa-masa sulit, dan pasanganmu tahu betul itu. Kamu juga peka terhadap ketidakadilan dalam hubungan dan tidak akan diam kalau merasa diperlakukan tidak baik. Namun kecenderungan waspada dan curiga bisa membuatmu terlalu sering menganalisis kata-kata atau sikap pasangan, mencari tanda-tanda masalah yang sebenarnya tidak ada. Kekhawatiran berlebihan ini bisa melelahkan hubungan, membuat pasangan merasa terus-menerus dicurigai padahal dia tidak melakukan kesalahan apa pun. *PR: Sekali ini, coba nikmati momen tenang bersama pasangan tanpa mencari-cari hal yang perlu dikhawatirkan.*",
        "keuangan": "Soal keuangan, sifat waspadamu membuatmu cenderung menyiapkan dana darurat yang cukup dan jarang mengambil risiko finansial yang gegabah. Kamu juga jujur dan adil dalam urusan uang dengan orang lain, tidak suka mengambil keuntungan yang bukan hakmu. Namun kekhawatiran berlebihan soal masa depan bisa membuatmu terlalu konservatif, sampai melewatkan peluang yang sebenarnya cukup aman untuk diambil. Kamu juga bisa menghabiskan energi mental yang besar untuk terus mengkhawatirkan skenario finansial terburuk yang kemungkinannya kecil terjadi. *PR: Tuliskan rencana dana daruratmu di atas kertas, lalu izinkan dirimu berhenti mengkhawatirkannya setelah itu.*",
        "kesehatan": "Kesetiaanmu pada rutinitas biasanya membuatmu disiplin menjaga kesehatan, kamu jarang melewatkan hal-hal yang sudah jadi kebiasaan baik. Namun sifat waspada yang berlebihan bisa membuat pikiranmu terus bekerja memikirkan kemungkinan buruk, termasuk soal kesehatanmu sendiri, yang berujung pada kecemasan yang menguras energi mental. Ketegangan ini kalau dibiarkan terus bisa berdampak fisik, seperti sulit tidur nyenyak atau tubuh yang selalu terasa tegang meski tidak sedang melakukan aktivitas berat. Kamu butuh cara untuk benar-benar melepaskan kewaspadaan itu sesekali. *PR: Coba satu aktivitas relaksasi sederhana setiap malam minggu ini, seperti peregangan ringan sebelum tidur.*",
    },
}
