"""Konten Shio — Ayam."""

AYAM_CONTENT = {
    "tagline": "🐓 Shio Ayam",
    "chip": "SHIO",
    "title": "Ayam — Sosok Rapi yang Percaya Diri",
    "p1_label": "Siapa Kamu",
    "p1": "Shio Ayam melambangkan ketelitian, kerapian, dan kepercayaan diri yang kuat. Kamu suka semua hal tertata dengan baik, mulai dari pekerjaan sampai penampilan sehari-hari. Kejujuranmu yang blak-blakan membuat orang lain tahu persis pendapatmu tentang sesuatu, tanpa perlu menebak-nebak lebih dulu. Kebiasaan menjaga segala sesuatu tetap rapi ini biasanya terlihat jelas di ruang kerjamu, jadwal harianmu, sampai cara kamu menyusun rencana untuk masa depan. Di lingkungan kerja, ketelitianmu membuatmu bisa diandalkan untuk pekerjaan yang butuh presisi tinggi, di mana kesalahan kecil sekalipun bisa berdampak besar. Rasa percaya diri yang kamu tunjukkan juga membuat orang lain cenderung mempercayai penilaianmu, terutama soal detail-detail yang mereka sendiri mungkin lewatkan.",
    "p2_label": "Kekuatan & yang Perlu Dijaga",
    "p2": "Ketelitian dan kepercayaan dirimu membuat orang lain percaya pada kualitas kerjamu. Kamu juga berani bicara jujur saat orang lain memilih diam. Sayangnya, kejujuran yang terlalu terus terang ini kadang terdengar seperti kritik yang menyakitkan, meski maksudmu sebenarnya baik. Standar tinggi yang kamu pegang untuk dirimu sendiri juga sering kamu terapkan ke orang lain tanpa sadar, sehingga mereka bisa merasa dinilai terlalu keras hanya karena tidak serapi atau seteliti dirimu. Hal ini bisa membuat sebagian orang merasa sungkan atau bahkan enggan bekerja sama denganmu, meski sebenarnya mereka menghargai standar tinggimu.",
    "quote": "Kejujuran akan lebih mudah diterima kalau disampaikan dengan sedikit lebih lembut.",
    "p3_label": "PR Kecil Buat Kamu",
    "p3": "Sebelum menyampaikan kritik, coba pikirkan dulu cara penyampaian yang lebih lembut, tanpa mengubah kejujuran dari isi pesannya. Cobalah teknik sederhana: sebutkan dulu satu hal yang sudah dilakukan dengan baik, sebelum menyampaikan bagian yang masih perlu diperbaiki. Latihan ini akan membuat orang lain lebih terbuka menerima masukanmu, tanpa mengurangi ketelitian dan kejujuran yang selama ini jadi ciri khasmu.",
    "domains": {
        "karir": "Ketelitianmu adalah aset besar di dunia kerja, kamu cocok di peran yang butuh presisi tinggi seperti quality assurance, audit, finance, atau posisi apa pun yang tidak memberi ruang untuk kesalahan kecil. Atasan mempercayaimu untuk hal-hal detail yang orang lain sering lewatkan. Namun kejujuranmu yang terus terang bisa terdengar seperti kritik pedas di telinga rekan kerja yang lebih sensitif, meski niatmu sebenarnya membantu. Standar tinggi yang kamu pegang untuk diri sendiri juga sering kamu terapkan ke tim tanpa sadar, sehingga sebagian orang merasa sungkan atau tertekan bekerja sama denganmu. *PR: Sebelum memberi masukan ke rekan kerja minggu ini, mulai dengan menyebut satu hal yang sudah dia lakukan dengan baik.*",
        "asmara": "Dalam hubungan, kejujuranmu membuat pasangan tahu persis di mana posisinya, tidak ada permainan tebak-tebakan denganmu. Kamu juga suka menjaga hubungan tetap rapi dan terencana, dari komunikasi sampai rencana masa depan. Namun standar tinggi yang kamu miliki bisa membuat pasangan merasa terus dinilai, terutama soal hal-hal kecil seperti kerapian atau cara melakukan sesuatu. Kejujuranmu yang blak-blakan, kalau tidak dibungkus dengan cukup lembut, bisa terasa menyakitkan bagi pasangan yang lebih sensitif, meski maksudmu sebenarnya baik dan ingin hubungan jadi lebih baik. *PR: Sampaikan satu kritik ke pasanganmu minggu ini dengan cara yang lebih lembut dari biasanya.*",
        "keuangan": "Soal keuangan, ketelitianmu membuatmu jago mengatur anggaran secara detail, kamu tahu persis ke mana uangmu pergi dan jarang terkejut dengan pengeluaran yang tidak terduga. Kerapian ini membuat kondisi finansialmu cenderung terkontrol dengan baik dibanding kebanyakan orang. Namun standar tinggi yang kamu pegang bisa membuatmu terlalu keras pada diri sendiri soal pengeluaran kecil, sampai merasa bersalah untuk hal-hal yang sebenarnya wajar dinikmati. Kamu juga cenderung terlalu vokal soal kebiasaan finansial orang lain di sekitarmu, yang kadang membuat mereka merasa dihakimi. *PR: Izinkan dirimu satu pengeluaran kecil minggu ini yang sifatnya murni untuk kesenangan, tanpa menghitung ulang berkali-kali.*",
        "kesehatan": "Kerapian dan ketelitianmu biasanya membuatmu disiplin soal pola hidup sehat, dari jadwal makan sampai rutinitas olahraga yang terstruktur dengan baik. Kamu juga cenderung cepat sadar kalau ada yang tidak beres dengan tubuhmu karena kamu memperhatikan detail dengan saksama. Namun standar tinggi yang kamu terapkan bisa membuatmu terlalu keras pada diri sendiri soal kesempurnaan fisik atau pola hidup, sampai sedikit penyimpangan dari rencana terasa seperti kegagalan besar. Perfeksionisme ini, kalau dibiarkan, bisa memicu stres yang sebenarnya tidak perlu. *PR: Kalau kamu melewatkan satu hari rutinitas sehatmu minggu ini, coba lanjutkan lagi besok tanpa menyalahkan diri sendiri.*",
    },
}
