"""Konten Shio — Babi."""

BABI_CONTENT = {
    "tagline": "🐷 Shio Babi",
    "chip": "SHIO",
    "title": "Babi — Sosok Tulus yang Penuh Kebaikan Hati",
    "p1_label": "Siapa Kamu",
    "p1": "Shio Babi melambangkan ketulusan, kemurahan hati, dan kejujuran yang sederhana. Kamu jarang berpikir buruk tentang orang lain, dan cenderung memberi kesempatan kedua meski sudah pernah dikecewakan. Kehadiranmu membuat orang-orang di sekitarmu merasa diterima apa adanya, tanpa banyak dihakimi. Kamu biasanya melihat sisi baik dari setiap orang terlebih dulu, sebelum menilai kesalahan atau kekurangan mereka. Dalam pertemanan, kamu adalah sosok yang murah hati, baik dalam berbagi waktu, tenaga, maupun materi, tanpa terlalu banyak menghitung untung rugi. Di lingkungan kerja, ketulusanmu membuat rekan-rekan merasa nyaman bekerja sama denganmu, karena mereka tahu kamu jarang punya agenda tersembunyi di balik setiap tindakanmu.",
    "p2_label": "Kekuatan & yang Perlu Dijaga",
    "p2": "Ketulusan dan kemurahan hatimu membuat orang lain merasa nyaman dan dihargai saat bersamamu. Kamu juga jarang menyimpan dendam terlalu lama. Namun sikap yang terlalu percaya ini kadang membuatmu mudah dimanfaatkan oleh orang-orang yang sebenarnya tidak berniat baik. Kebaikan hatimu yang tanpa syarat ini bisa membuat sebagian orang sengaja mengambil keuntungan dari kesediaanmu untuk selalu membantu, sementara kamu sendiri jarang meminta imbalan apa pun. Kalau tidak diimbangi kehati-hatian, pola ini bisa berulang terus-menerus tanpa kamu sadari.",
    "quote": "Kebaikan hati akan lebih aman kalau disertai sedikit kehati-hatian dalam memilih kepada siapa kamu memberikannya.",
    "p3_label": "PR Kecil Buat Kamu",
    "p3": 'Coba perhatikan lebih saksama pola perlakuan orang-orang di sekitarmu, dan beri batasan yang wajar kepada mereka yang selama ini hanya memanfaatkan kebaikanmu. Latih dirimu untuk sesekali berkata "tidak" pada permintaan yang terasa tidak adil, tanpa harus merasa bersalah karenanya. Ingat, kebaikan hati yang sehat tetap bisa berjalan bersama batasan yang jelas, dan itu justru membuat kebaikanmu lebih berkelanjutan.',
    "domains": {
        "karir": "Ketulusan dan kemurahan hatimu membuat rekan kerja senang berkolaborasi denganmu, kamu jarang punya agenda tersembunyi dan itu membuatmu dipercaya di lingkungan kerja mana pun. Kamu cocok di peran yang melibatkan kerja sama tim atau pelayanan kepada orang lain, karena kamu tulus ingin membantu tanpa banyak menghitung untung-rugi. Namun ketulusan ini bisa dimanfaatkan rekan kerja yang kurang bertanggung jawab, mereka bisa membebankan tugasnya padamu karena tahu kamu jarang menolak permintaan tolong. Kamu juga cenderung kurang vokal memperjuangkan haknya sendiri, seperti kenaikan gaji atau pengakuan atas kerja kerasmu. *PR: Sekali ini, tolak satu permintaan tolong yang sebenarnya di luar tanggung jawabmu di kantor.*",
        "asmara": "Dalam hubungan, ketulusanmu membuat pasangan merasa benar-benar diterima apa adanya, kamu jarang menghakimi kekurangan pasangan dan selalu memberi kesempatan kedua. Kamu juga murah hati dalam mencintai, tidak pelit memberi waktu dan perhatian. Namun sikap yang terlalu percaya ini bisa membuatmu gampang dimanfaatkan oleh pasangan yang kurang bertanggung jawab, kamu terus memaafkan meski pola kesalahan yang sama berulang. Kamu perlu belajar bahwa memberi kesempatan kedua itu baik, tapi ada batas wajar sebelum itu berubah jadi membiarkan diri terus dirugikan. *PR: Perhatikan satu pola dalam hubunganmu yang selama ini terus berulang, dan bicarakan dengan pasangan tanpa langsung memaafkan begitu saja.*",
        "keuangan": "Soal keuangan, kemurahan hatimu membuatmu senang berbagi dengan orang terdekat, entah lewat traktiran, bantuan, atau hadiah tanpa alasan khusus. Kamu percaya rezeki akan berputar kalau kamu murah hati pada orang lain. Namun sikap yang terlalu percaya dan murah hati ini bisa membuatmu rentan dimanfaatkan orang yang sengaja mendekat karena tahu kamu mudah membantu secara finansial. Kamu juga jarang mencatat atau menagih kembali uang yang kamu pinjamkan, sampai tanpa sadar kondisi keuanganmu sendiri jadi terganggu karena terlalu banyak membantu orang lain. *PR: Buat batasan jelas soal berapa banyak yang bisa kamu bantu bulan ini, dan patuhi batasan itu.*",
        "kesehatan": "Sifatmu yang santai dan jarang menyimpan dendam membuat bebanmu secara mental cenderung lebih ringan dibanding orang lain, kamu tidak mudah stres memikirkan hal-hal yang sudah lewat. Namun sikap terlalu percaya dan mudah memaafkan bisa membuatmu menahan kekecewaan yang seharusnya diproses, bukan sekadar dilupakan begitu saja, dan itu bisa menumpuk jadi beban emosional yang tidak terlihat. Kamu juga cenderung kurang tegas menjaga waktu istirahatmu sendiri karena selalu memprioritaskan membantu orang lain lebih dulu. *PR: Jadwalkan satu waktu khusus minggu ini yang benar-benar untuk dirimu sendiri, tanpa bisa diganggu urusan membantu orang lain.*",
    },
}
