"""Konten Shio — Kambing."""

KAMBING_CONTENT = {
    "tagline": "🐐 Shio Kambing",
    "chip": "SHIO",
    "title": "Kambing — Jiwa Lembut yang Penuh Empati",
    "p1_label": "Siapa Kamu",
    "p1": "Shio Kambing melambangkan kelembutan hati, kreativitas, dan kepedulian yang tulus terhadap orang lain. Kamu punya sisi artistik dan suka menciptakan suasana yang nyaman di sekitarmu. Kepekaanmu terhadap perasaan orang lain membuatmu sering jadi tempat curhat yang dipercaya banyak teman. Kamu biasanya punya cara pandang yang lembut terhadap dunia, dan lebih tertarik menciptakan sesuatu yang indah atau menenangkan dibanding bersaing secara langsung dengan orang lain. Dalam lingkungan sosial, kamu sering jadi sosok yang membuat orang lain merasa diterima apa adanya, tanpa banyak dihakimi. Sisi kreatifmu juga sering muncul dalam hal-hal sehari-hari, seperti caramu menata ruangan, memilih pakaian, atau menciptakan suasana hangat dalam sebuah pertemuan.",
    "p2_label": "Kekuatan & yang Perlu Dijaga",
    "p2": "Kepedulian dan kreativitasmu membuat orang lain merasa nyaman dan dihargai saat bersamamu. Kamu juga punya kemampuan menciptakan hal-hal indah dari sudut pandang yang berbeda. Namun kelembutan hati ini kadang membuatmu terlalu bergantung pada validasi atau persetujuan orang lain sebelum merasa yakin dengan pilihanmu sendiri. Kebutuhan akan persetujuan ini bisa membuatmu ragu mengambil keputusan penting tanpa mendengar banyak pendapat orang lain terlebih dulu, bahkan untuk hal-hal yang sebenarnya kamu sendiri sudah tahu jawabannya. Kamu juga bisa jadi terlalu sensitif terhadap kritik, sampai kritik kecil terasa seperti penolakan besar terhadap dirimu secara keseluruhan.",
    "quote": "Pendapat orang lain penting, tapi keyakinanmu pada dirimu sendiri jauh lebih penting lagi.",
    "p3_label": "PR Kecil Buat Kamu",
    "p3": "Coba ambil satu keputusan kecil berdasarkan penilaianmu sendiri, tanpa meminta persetujuan orang lain terlebih dulu. Latih kepercayaan ini dengan cara bertahap, mulai dari keputusan yang risikonya kecil seperti memilih tempat makan, sampai akhirnya kamu terbiasa mempercayai penilaianmu sendiri untuk hal-hal yang lebih besar. Ingatkan juga dirimu bahwa kritik terhadap satu keputusan bukan berarti penolakan terhadap dirimu secara keseluruhan.",
    "domains": {
        "karir": "Sisi kreatif dan empatimu membuatmu cocok di pekerjaan yang melibatkan seni, desain, konten, atau bidang apa pun yang butuh sentuhan personal dan kepekaan rasa. Kamu juga jago menciptakan suasana kerja yang nyaman, dan rekan-rekan senang berkolaborasi denganmu karena kamu jarang membuat suasana jadi kaku atau kompetitif secara berlebihan. Namun kebutuhan akan validasi bisa membuatmu ragu mengajukan ide sendiri sebelum yakin orang lain akan menyukainya, sehingga kontribusimu yang sebenarnya berharga jadi tertahan. Kamu juga cenderung sulit bersaing secara terang-terangan untuk promosi atau pengakuan, karena merasa canggung menonjolkan diri sendiri. *PR: Ajukan satu ide kreatifmu di tempat kerja tanpa menunggu validasi orang lain lebih dulu.*",
        "asmara": "Dalam hubungan, kelembutan dan empatimu membuat pasangan merasa benar-benar dipahami, kamu peka terhadap perasaan mereka bahkan sebelum mereka mengungkapkannya. Kamu juga suka menciptakan momen-momen romantis yang penuh perhatian pada detail kecil. Namun kebutuhan akan persetujuan bisa membuatmu terlalu sering mengesampingkan keinginanmu sendiri demi menyenangkan pasangan, sampai kebutuhanmu sendiri jarang benar-benar tersampaikan. Kamu juga bisa sangat terpukul oleh kritik kecil dari pasangan, menganggapnya sebagai tanda hubungan sedang bermasalah, padahal belum tentu demikian. *PR: Sampaikan satu keinginanmu sendiri ke pasangan minggu ini, tanpa dibungkus permintaan maaf berlebihan.*",
        "keuangan": "Soal keuangan, seleramu yang halus membuatmu cenderung tertarik membelanjakan uang untuk hal-hal yang indah atau berkualitas, entah itu barang seni, dekorasi, atau pengalaman yang estetis. Kamu menghargai keindahan lebih dari sekadar fungsi semata. Namun kebutuhan validasi sosial bisa membuatmu membelanjakan uang untuk mengikuti standar orang lain, entah demi terlihat mapan atau supaya diterima di lingkungan tertentu, meski itu sebenarnya di luar kemampuanmu. Kamu juga cenderung ragu menegosiasikan harga atau meminta kompensasi yang layak, karena tidak nyaman terlihat terlalu menuntut. *PR: Buat anggaran khusus untuk hal-hal estetis yang kamu suka, supaya pengeluaranmu lebih terkontrol tanpa harus merasa bersalah.*",
        "kesehatan": "Kepekaanmu terhadap suasana membuatmu mudah terpengaruh energi di sekitarmu, kalau lingkunganmu penuh tekanan atau konflik, kamu bisa ikut merasa lelah secara emosional meski masalahnya bukan langsung soal dirimu. Kamu butuh ruang yang tenang dan indah untuk memulihkan energi, dan ini bukan sesuatu yang boleh kamu anggap remeh. Kebiasaan terlalu memikirkan pendapat orang lain juga bisa memicu kecemasan berlebihan, terutama saat merasa dinilai atau dikritik. Penting untukmu punya ruang atau aktivitas kreatif sebagai pelarian yang sehat dari tekanan sosial yang kamu rasakan. *PR: Sisihkan waktu untuk satu aktivitas kreatif minggu ini, khusus untuk dirimu sendiri, tanpa tujuan menyenangkan orang lain.*",
    },
}
