"""Konten Shio — Kelinci."""

KELINCI_CONTENT = {
    "tagline": "🐰 Shio Kelinci",
    "chip": "SHIO",
    "title": "Kelinci — Sosok Lembut yang Bijaksana",
    "p1_label": "Siapa Kamu",
    "p1": "Shio Kelinci melambangkan kelembutan, kehati-hatian, dan kebijaksanaan dalam bersikap. Kamu cenderung menghindari konflik dan lebih memilih menyelesaikan masalah dengan cara yang halus. Ketenanganmu membuat orang-orang di sekitarmu merasa nyaman, karena kamu jarang membuat suasana menjadi tegang tanpa alasan yang jelas. Dalam pergaulan, kamu biasanya jadi sosok yang menenangkan ketika suasana sedang panas, karena caramu bicara yang lembut jarang memancing amarah orang lain. Di tempat kerja, kehati-hatianmu membuatmu jarang membuat kesalahan yang tergesa-gesa, karena kamu selalu memastikan situasinya aman sebelum melangkah. Kamu juga cenderung punya selera yang halus dan menghargai keindahan, baik dalam cara berpakaian, menata ruang, maupun caramu memilih kata-kata saat berbicara dengan orang lain.",
    "p2_label": "Kekuatan & yang Perlu Dijaga",
    "p2": "Kehati-hatian dan kepekaanmu membuatmu jarang terjebak dalam keputusan gegabah. Kamu juga pandai menjaga hubungan baik dengan banyak orang. Namun kebiasaan menghindari konflik ini kadang membuatmu memendam ketidaknyamanan sendiri demi menjaga suasana tetap damai, sampai akhirnya kamu sendiri yang merasa terbebani. Kecenderungan untuk selalu mengalah demi kedamaian ini bisa membuat orang lain, tanpa mereka sadari, terbiasa mengambil keuntungan dari sikap lembutmu. Kamu juga bisa kehilangan kesempatan penting karena terlalu takut sikapmu akan dianggap terlalu memaksa atau mengganggu kenyamanan orang lain.",
    "quote": "Menjaga kedamaian itu baik, tapi bukan berarti kamu harus selalu mengalah pada dirimu sendiri.",
    "p3_label": "PR Kecil Buat Kamu",
    "p3": 'Ketika ada sesuatu yang mengganggumu, coba sampaikan dengan lembut kepada orang yang bersangkutan, alih-alih memilih diam demi menghindari konflik. Kamu bisa mulai dengan kalimat sederhana seperti "aku sebenarnya kurang nyaman kalau...", yang tetap terdengar lembut tapi jujur. Latih juga dirimu mengenali perbedaan antara konflik yang sehat, yang membantu hubungan jadi lebih jelas, dengan konflik yang benar-benar merusak, supaya kamu tidak menghindari semua bentuk ketidaksepakatan secara membabi buta.',
    "domains": {
        "karir": "Di tempat kerja, kehati-hatian dan seleramu yang halus membuatmu cocok di peran yang butuh diplomasi dan estetika, seperti mediasi antar tim, desain, atau posisi yang berhubungan langsung dengan klien yang sensitif. Kamu jarang membuat suasana kerja jadi tegang, dan itu membuat rekan-rekan merasa nyaman berdiskusi denganmu. Namun kecenderungan menghindari konflik ini bisa membuatmu enggan menyampaikan ketidaksetujuan secara langsung ke atasan atau rekan kerja, sehingga idemu yang sebenarnya bagus jadi tidak tersampaikan dengan maksimal. Kamu juga berisiko dilewati untuk promosi karena dianggap terlalu 'aman' dan kurang menonjolkan diri, padahal kemampuanmu sebenarnya setara atau lebih baik dari rekan lain yang lebih vokal. *PR: Sampaikan satu ide atau pendapatmu secara langsung dalam rapat berikutnya, tanpa menunggu ditanya dulu.*",
        "asmara": "Dalam hubungan, kelembutanmu membuat pasangan merasa sangat nyaman dan jarang merasa terancam olehmu. Kamu juga pandai menciptakan suasana romantis yang tenang, bukan yang dramatis, dan itu jadi kekuatan tersendiri buat pasangan yang mencari ketenangan. Tapi kebiasaan menghindari konflik bisa membuatmu memendam kekecewaan terhadap pasangan sampai menumpuk, dan ketika akhirnya meledak, pasangan justru bingung karena selama ini kamu terlihat baik-baik saja. Kamu juga perlu waspada terhadap kecenderungan mengalah terus-menerus demi menghindari pertengkaran, sampai kebutuhanmu sendiri jarang benar-benar terpenuhi dalam hubungan itu. *PR: Sampaikan satu hal yang selama ini mengganjal di hati ke pasanganmu minggu ini, dengan cara yang lembut tapi jujur.*",
        "keuangan": "Soal keuangan, kehati-hatianmu membuatmu jarang terjebak pengeluaran impulsif atau investasi berisiko tinggi yang tidak kamu pahami. Kamu juga punya selera yang baik dalam memilih barang berkualitas yang tahan lama, dibanding membeli banyak barang murah yang cepat rusak. Namun kecenderungan menghindari ketidaknyamanan bisa membuatmu enggan bernegosiasi soal harga atau gaji, karena merasa canggung atau takut dianggap terlalu menuntut. Ini bisa membuat nilai finansialmu sebenarnya lebih rendah dari yang seharusnya kamu dapatkan. Kamu juga cenderung menghindari topik keuangan yang sensitif dengan pasangan atau keluarga, padahal keterbukaan soal ini justru penting untuk perencanaan jangka panjang. *PR: Coba negosiasikan satu hal soal harga atau kompensasi yang selama ini kamu hindari.*",
        "kesehatan": "Ketenanganmu secara alami membuat sistem tubuhmu relatif tidak mudah stres berlebihan, dan kamu cenderung punya kebiasaan menjaga diri dengan cara yang halus, seperti tidur cukup dan menjaga penampilan. Namun kebiasaan memendam perasaan dan menghindari konflik bisa berdampak pada kesehatan secara diam-diam, tekanan emosional yang tidak tersalurkan sering muncul sebagai keluhan fisik seperti sakit kepala, gangguan pencernaan, atau kelelahan yang tidak jelas sebabnya. Kamu perlu punya saluran yang sehat untuk melepaskan emosi yang selama ini kamu simpan sendiri, entah lewat jurnal, olahraga, atau bicara dengan orang yang benar-benar kamu percaya. *PR: Coba tuliskan satu hal yang selama ini kamu pendam, tanpa perlu menunjukkannya ke siapa pun.*",
    },
}
