"""Konten Shio — Kerbau."""

KERBAU_CONTENT = {
    "tagline": "🐂 Shio Kerbau",
    "chip": "SHIO",
    "title": "Kerbau — Sosok Tekun yang Bisa Diandalkan",
    "p1_label": "Siapa Kamu",
    "p1": "Shio Kerbau melambangkan ketekunan, kejujuran, dan kerja keras yang konsisten. Kamu bukan tipe yang suka mencari jalan pintas; kamu lebih memilih menyelesaikan sesuatu langkah demi langkah sampai benar-benar tuntas. Orang-orang di sekitarmu tahu bahwa kata-katamu bisa dipegang, karena kamu jarang mengingkari janji. Dalam pekerjaan, ketekunanmu membuatmu unggul di tugas-tugas yang butuh waktu lama dan konsistensi tinggi, jenis pekerjaan yang membuat banyak orang lain menyerah di tengah jalan. Kamu juga jarang tergoda mengambil jalan pintas meski itu bisa mempercepat hasil, karena bagimu proses yang benar sama pentingnya dengan hasil akhirnya. Di lingkungan keluarga atau pertemanan, kamu adalah sosok yang selalu ada, sosok yang orang tahu pasti bisa diandalkan meski situasinya sedang sulit.",
    "p2_label": "Kekuatan & yang Perlu Dijaga",
    "p2": "Keteguhan dan kejujuranmu membuat orang lain merasa aman bekerja sama denganmu dalam jangka panjang. Kamu juga tidak mudah goyah oleh tekanan atau opini orang lain. Sayangnya, keteguhan itu kadang berubah menjadi keras kepala, membuatmu sulit menerima cara pandang baru meski cara pandang itu sebenarnya lebih baik. Kekukuhan ini juga bisa membuatmu terjebak dalam cara lama yang sebenarnya sudah tidak lagi efektif, hanya karena itu cara yang sudah kamu kenal dan kuasai. Orang di sekitarmu mungkin merasa sungkan menyampaikan kritik atau masukan, karena tahu betapa sulitnya membuatmu berubah pikiran begitu keputusan sudah diambil.",
    "quote": "Keteguhan itu berharga, tapi kebesaran hati untuk berubah pikiran juga tanda kekuatan.",
    "p3_label": "PR Kecil Buat Kamu",
    "p3": "Coba dengarkan satu pendapat yang berbeda dari caramu biasa melakukan sesuatu, dan pertimbangkan dengan pikiran terbuka sebelum menolaknya. Alih-alih langsung mempertahankan cara lamamu, coba tanyakan dulu alasan di balik pendapat berbeda itu, dan bandingkan hasilnya secara objektif. Kamu juga bisa mencoba satu kali melakukan sesuatu dengan cara baru dalam skala kecil, sebagai eksperimen, sebelum menilai apakah cara itu lebih baik atau tidak dari kebiasaanmu.",
    "domains": {
        "karir": "Dalam pekerjaan, kamu adalah tipe yang akan tetap ada mengerjakan sesuatu sampai benar-benar tuntas, bahkan saat rekan-rekan lain sudah mulai kehilangan semangat di tengah proyek panjang. Ini membuatmu jadi andalan untuk peran yang butuh konsistensi dan ketahanan, seperti operasional, quality control, atau posisi yang menuntut disiplin tinggi dalam jangka waktu lama. Atasan biasanya mempercayaimu memegang tanggung jawab besar karena tahu kamu tidak akan lari dari masalah. Tantangannya, kamu bisa terlalu lama bertahan di pekerjaan atau cara kerja yang sebenarnya sudah tidak sehat untukmu, hanya karena merasa harus loyal atau karena belum terbiasa dengan perubahan. Kamu juga perlu belajar bahwa meminta kenaikan posisi atau gaji bukan berarti tidak tahu diri, tapi bagian wajar dari mengakui kerja kerasmu sendiri. *PR: Coba ajukan satu hal yang selama ini kamu pendam soal pekerjaanmu ke atasan minggu ini.*",
        "asmara": "Dalam hubungan, kesetiaanmu terasa jelas dan pasangan biasanya merasa aman bersamamu karena kamu bukan tipe yang mudah tergoda berpindah hati. Kamu juga menunjukkan cinta lewat tindakan nyata dan konsisten, bukan lewat kata-kata manis yang berlebihan, dan itu justru jadi bentuk kepercayaan yang paling kuat bagi orang yang benar-benar mengenalmu. Namun keteguhanmu bisa berubah jadi kekakuan kalau pasangan butuh kamu beradaptasi dengan caranya, misalnya soal cara berkomunikasi atau menyelesaikan konflik. Kamu cenderung merasa caramu sendiri sudah benar, sehingga kompromi terasa seperti kekalahan, padahal hubungan yang sehat butuh dua orang yang mau sama-sama menyesuaikan diri. *PR: Tanyakan ke pasanganmu satu hal yang menurutnya bisa kamu perbaiki, dan dengarkan tanpa langsung membela diri.*",
        "keuangan": "Soal uang, kamu adalah tipe yang paling bisa diandalkan untuk menabung secara konsisten dan tidak mudah tergoda pengeluaran impulsif. Kamu percaya bahwa kekayaan dibangun pelan-pelan lewat kerja keras dan kedisiplinan, bukan lewat jalan pintas yang berisiko. Prinsip ini membuat kondisi finansialmu cenderung stabil dalam jangka panjang dibanding kebanyakan orang. Namun kehati-hatianmu yang berlebihan bisa membuatmu melewatkan peluang investasi yang sebenarnya masuk akal, hanya karena terasa asing atau belum pernah kamu coba sebelumnya. Kamu juga cenderung menunda menikmati hasil kerja kerasmu sendiri, terus menabung untuk masa depan sampai lupa bahwa masa sekarang juga layak dirayakan sesekali. *PR: Riset satu instrumen investasi baru minggu ini, meski hanya sekadar untuk memahami cara kerjanya.*",
        "kesehatan": "Ketahanan fisik dan mentalmu biasanya cukup kuat, dan kamu jarang mengeluh soal capek meski beban kerjamu berat. Sayangnya, kebiasaan ini bisa membuatmu mengabaikan sinyal-sinyal awal kelelahan atau stres, karena kamu terbiasa 'tahan banting' dan menganggap istirahat sebagai sesuatu yang bisa ditunda terus. Pola makan dan tidurmu juga bisa jadi kaku, kamu nyaman dengan rutinitas yang sama setiap hari, yang bagus untuk konsistensi tapi kadang membuatmu kurang fleksibel menyesuaikan pola hidup saat tubuh sebenarnya butuh sesuatu yang berbeda. Penting untukmu belajar bahwa istirahat bukan tanda kelemahan, tapi bagian dari menjaga daya tahan jangka panjang yang selama ini jadi kekuatanmu. *PR: Jadwalkan satu hari penuh minggu ini khusus untuk benar-benar istirahat tanpa merasa bersalah.*",
    },
}
