"""Konten Shio — Kuda."""

KUDA_CONTENT = {
    "tagline": "🐴 Shio Kuda",
    "chip": "SHIO",
    "title": "Kuda — Jiwa Bebas yang Energik",
    "p1_label": "Siapa Kamu",
    "p1": "Shio Kuda dikenal sebagai simbol kebebasan, semangat, dan energi yang tidak pernah habis. Kamu suka bergerak, mencoba hal baru, dan tidak betah terlalu lama terjebak dalam rutinitas yang membosankan. Semangatmu yang tinggi sering menular ke orang-orang di sekitarmu, membuat suasana jadi lebih hidup. Kamu biasanya tidak nyaman kalau harus duduk diam terlalu lama tanpa aktivitas, dan selalu mencari cara untuk membuat harimu terasa lebih dinamis, entah lewat pekerjaan, hobi, atau sekadar jalan-jalan tanpa rencana pasti. Dalam pergaulan, energimu yang positif membuat orang lain senang diajak berkegiatan bersamamu, karena kamu jarang membuat suasana terasa berat atau membosankan. Di tempat kerja, kamu cenderung lebih bersemangat mengerjakan proyek yang bervariasi dibanding tugas yang berulang dan monoton.",
    "p2_label": "Kekuatan & yang Perlu Dijaga",
    "p2": "Energi dan semangat petualanganmu membuat orang lain terinspirasi untuk keluar dari rutinitas mereka juga. Kamu juga mudah bergaul dengan berbagai kalangan. Namun kebebasan yang kamu junjung tinggi ini kadang membuatmu sulit berkomitmen pada satu hal dalam jangka panjang, karena selalu ada godaan untuk mencoba yang baru. Kecenderungan berpindah dari satu hal ke hal lain ini bisa membuat beberapa rencana besarmu tidak pernah benar-benar selesai, karena perhatianmu sudah teralihkan ke sesuatu yang lebih menarik. Dalam hubungan, sikap ini juga bisa membuat pasangan atau sahabat merasa tidak yakin seberapa jauh mereka bisa mengandalkan komitmenmu.",
    "quote": "Kebebasan sejati justru terasa lebih utuh ketika kamu berani berkomitmen pada apa yang benar-benar penting.",
    "p3_label": "PR Kecil Buat Kamu",
    "p3": "Pilih satu komitmen yang sudah kamu buat, lalu jaga konsistensinya tanpa tergoda beralih ke hal baru yang lain. Untuk membantu, coba tuliskan alasan awal kenapa kamu memilih komitmen itu, dan baca ulang setiap kali godaan untuk berpindah muncul. Kamu juga bisa memberi dirimu penghargaan kecil setiap kali berhasil bertahan satu tahap penuh, supaya konsistensi terasa menyenangkan, bukan sekadar kewajiban.",
    "domains": {
        "karir": "Semangat dan fleksibilitasmu membuatmu cocok di pekerjaan yang penuh variasi dan dinamika, seperti event organizer, sales lapangan, atau peran yang mengharuskanmu berpindah tempat dan bertemu banyak orang baru. Kamu cepat beradaptasi dengan lingkungan baru dan jarang merasa canggung di situasi yang asing. Namun kecenderunganmu mudah bosan bisa membuatmu berpindah pekerjaan atau proyek terlalu sering sebelum benar-benar menuai hasil dari yang sedang kamu kerjakan. Rekam jejak yang terlihat 'loncat-loncat' ini bisa membuat orang lain ragu mempercayakan tanggung jawab jangka panjang padamu, meski sebenarnya kamu punya kemampuan yang cukup untuk itu. *PR: Pilih satu proyek yang sedang berjalan, dan komit menyelesaikannya sampai tuntas sebelum memulai yang baru.*",
        "asmara": "Dalam asmara, energi positifmu membuat hubungan terasa seru dan penuh kejutan, pasanganmu jarang merasa bosan karena kamu selalu punya ide aktivitas baru. Kamu juga tipe yang terbuka dan jujur soal apa yang kamu rasakan, tidak suka menyimpan drama berkepanjangan. Namun rasa takut terjebak dalam rutinitas bisa membuatmu ragu berkomitmen serius, karena merasa komitmen sama dengan kehilangan kebebasan. Pasangan mungkin merasa tidak yakin seberapa jauh mereka bisa mengandalkanmu untuk jangka panjang, terutama kalau kamu sering menghindari pembicaraan soal masa depan hubungan. *PR: Ajak pasanganmu bicara terbuka soal satu rencana jangka panjang, tanpa menghindar seperti biasanya.*",
        "keuangan": "Soal uang, sifat spontanmu membuatmu tidak ragu mengeluarkan uang untuk pengalaman baru, entah itu jalan-jalan, hobi, atau mencoba sesuatu yang belum pernah kamu lakukan. Kamu percaya hidup harus dinikmati, bukan cuma ditabung untuk masa depan yang belum pasti. Namun kebiasaan ini bisa membuat tabunganmu jarang benar-benar bertambah, karena begitu ada uang lebih, dorongan untuk segera menggunakannya untuk hal baru selalu muncul. Kamu perlu sistem yang membuat menabung terasa otomatis, karena kalau mengandalkan niat semata, godaan untuk membelanjakannya biasanya menang. *PR: Buat rekening tabungan terpisah yang auto-debet setiap gajian, supaya kamu tidak sempat tergoda memakainya.*",
        "kesehatan": "Energimu yang tinggi membuatmu jarang diam, dan itu bagus untuk kebugaran fisik karena tubuhmu terbiasa aktif bergerak. Kamu juga cenderung cepat bosan dengan rutinitas olahraga yang monoton, jadi olahraga yang bervariasi atau berkelompok biasanya lebih cocok buatmu dibanding rutin sendirian. Namun gaya hidupmu yang serba cepat dan berpindah-pindah bisa membuat pola makan dan tidurmu jadi tidak teratur, kamu mungkin sering melewatkan waktu makan atau begadang karena terlalu asyik dengan aktivitas baru. Ketidaktetapan jadwal ini, kalau dibiarkan terus, bisa berdampak ke stamina jangka panjangmu. *PR: Coba tetapkan satu jam tidur yang konsisten selama seminggu ke depan, meski hari-harimu terasa berbeda-beda.*",
    },
}
