"""Konten Shio — Macan."""

MACAN_CONTENT = {
    "tagline": "🐯 Shio Macan",
    "chip": "SHIO",
    "title": "Macan — Pemberani yang Penuh Semangat",
    "p1_label": "Siapa Kamu",
    "p1": "Shio Macan dikenal sebagai simbol keberanian dan semangat juang yang besar. Kamu punya energi yang membuatmu tidak takut menghadapi tantangan, bahkan cenderung mencari tantangan itu sendiri. Kehadiranmu terasa penuh percaya diri, dan orang lain sering melihatmu sebagai sosok yang berani bertindak lebih dulu. Sejak muda, kamu mungkin sudah terbiasa mengambil risiko yang bagi orang lain terasa menakutkan, entah itu mencoba hal baru, membela pendapatmu di depan umum, atau memulai sesuatu tanpa jaminan keberhasilan. Di lingkungan kerja, energi ini membuatmu cocok mengisi peran yang butuh keputusan cepat dan keberanian mengambil tindakan, terutama saat orang lain masih ragu atau menunggu arahan. Karisma alami yang kamu miliki juga membuat orang lain cenderung mengikuti arahmu, bahkan tanpa kamu perlu memaksa.",
    "p2_label": "Kekuatan & yang Perlu Dijaga",
    "p2": "Keberanian dan semangatmu membuat orang lain terdorong untuk ikut berani mengambil risiko yang sehat. Kamu juga punya kharisma alami yang membuat orang memperhatikanmu. Namun semangat yang menggebu itu kadang membuatmu bertindak terlalu impulsif, tanpa sempat memikirkan konsekuensi jangka panjangnya. Dorongan untuk selalu bertindak cepat ini bisa membuatmu melewatkan detail penting yang sebenarnya krusial, atau membuat keputusan besar hanya berdasarkan semangat sesaat. Di hubungan dengan orang lain, keberanianmu yang terlalu dominan kadang membuat orang di sekitarmu merasa tertinggal atau kesulitan mengimbangi langkahmu yang cepat.",
    "quote": "Keberanian yang matang tahu kapan harus menyerang dan kapan harus menunggu waktu yang tepat.",
    "p3_label": "PR Kecil Buat Kamu",
    "p3": "Sebelum mengambil keputusan besar, coba beri jeda satu hari untuk memikirkannya ulang, alih-alih langsung bertindak seperti biasanya. Gunakan jeda itu untuk menuliskan kemungkinan terbaik dan terburuk dari keputusan itu, supaya kamu punya gambaran lebih lengkap sebelum melangkah. Kamu juga bisa melatih diri bertanya kepada satu orang yang kamu percaya sebelum mengambil keputusan besar, bukan untuk meminta izin, tapi untuk mendengar sudut pandang yang mungkin belum kamu pertimbangkan.",
    "domains": {
        "karir": "Di lingkungan kerja, keberanianmu membuatmu cocok mengambil peran yang butuh inisiatif dan keputusan cepat, seperti memimpin proyek baru, membuka lini bisnis yang belum pernah dicoba, atau tampil di depan saat situasi genting. Kamu tidak takut mengambil tanggung jawab besar, dan energi ini sering menular ke tim, membuat mereka ikut berani mengambil langkah yang tadinya terasa menakutkan. Namun sisi impulsifmu bisa membuatmu mengambil keputusan besar tanpa mempertimbangkan data atau masukan tim secara utuh, yang berisiko menimbulkan masalah di kemudian hari. Kamu juga cenderung ingin semua berjalan sesuai kecepatanmu, sampai lupa bahwa tidak semua orang punya ritme kerja yang sama, dan itu bisa membuat rekan kerja merasa tertekan atau tertinggal. *PR: Sebelum mengambil keputusan besar minggu ini, minta pendapat dua rekan kerja dulu.*",
        "asmara": "Dalam asmara, semangat dan kepercayaan dirimu membuatmu jadi sosok yang menarik perhatian, kamu tidak ragu mengejar apa yang kamu mau, termasuk soal perasaan. Pasanganmu biasanya merasa hidup jadi lebih penuh warna dan petualangan bersamamu, karena kamu jarang membiarkan hubungan terasa monoton. Tapi dominasimu dalam mengambil keputusan bisa membuat pasangan merasa pendapatnya kurang didengar, terutama saat kamu sudah yakin dengan satu arah dan langsung bergerak tanpa banyak diskusi. Kamu juga perlu waspada terhadap kecenderungan bosan kalau hubungan terasa terlalu stabil dan tanpa tantangan, padahal hubungan yang matang justru dibangun dari momen-momen tenang, bukan cuma dari gairah yang menggebu. *PR: Tanyakan pendapat pasanganmu dulu sebelum mengambil keputusan penting berikutnya dalam hubungan kalian.*",
        "keuangan": "Soal keuangan, keberanianmu membuatmu tidak takut mengambil risiko yang sebenarnya bisa mendatangkan hasil besar, entah lewat usaha sendiri, investasi yang agresif, atau peluang yang orang lain anggap terlalu berisiko. Kamu juga punya keyakinan diri yang membuatmu percaya usahamu akan membuahkan hasil. Namun dorongan untuk bertindak cepat tanpa perhitungan matang bisa membuatmu mengambil keputusan finansial besar hanya berdasarkan semangat sesaat, tanpa riset yang cukup. Kamu perlu belajar menahan diri sejenak sebelum menandatangani sesuatu yang besar, karena keputusan finansial yang diambil dalam kondisi terlalu bersemangat sering kali menyesatkan di kemudian hari. *PR: Tunda satu keputusan finansial besar selama tiga hari sebelum benar-benar memutuskannya.*",
        "kesehatan": "Energimu yang besar biasanya membuatmu jarang sakit dan cepat pulih kalau sedang tidak fit, karena tubuhmu memang terbiasa aktif bergerak. Kamu juga cenderung menikmati olahraga yang menantang adrenalin, bukan sekadar rutinitas yang datar. Tapi semangatmu yang menggebu bisa membuatmu memaksakan diri terlalu keras, entah dalam olahraga, pekerjaan, atau aktivitas lain, sampai tubuh sebenarnya butuh jeda tapi kamu abaikan sinyalnya. Kamu juga tipe yang kurang sabar menunggu proses penyembuhan kalau sedang cedera atau sakit, ingin cepat kembali beraktivitas seperti biasa padahal tubuh belum sepenuhnya siap. *PR: Kalau tubuhmu memberi sinyal lelah minggu ini, coba benar-benar berhenti sejenak, bukan memaksakan diri lanjut.*",
    },
}
