"""Konten Shio — Monyet."""

MONYET_CONTENT = {
    "tagline": "🐒 Shio Monyet",
    "chip": "SHIO",
    "title": "Monyet — Si Cerdas yang Penuh Ide",
    "p1_label": "Siapa Kamu",
    "p1": "Shio Monyet dikenal sebagai simbol kecerdasan, kelincahan, dan kemampuan memecahkan masalah dengan cara-cara kreatif. Kamu cepat menangkap pola dan sering menemukan solusi yang tidak terpikirkan orang lain. Rasa humor dan keluwesanmu membuat orang-orang di sekitarmu merasa senang berada di dekatmu. Kamu biasanya punya banyak ide sekaligus, dan senang menghubungkan hal-hal yang sekilas tidak berkaitan menjadi solusi yang unik. Di lingkungan kerja, kemampuan ini membuatmu cocok mengisi peran yang butuh fleksibilitas dan pemikiran cepat, terutama saat menghadapi masalah yang belum pernah ditemui sebelumnya. Dalam pergaulan, kamu adalah tipe orang yang bisa mencairkan suasana kaku hanya dengan satu candaan yang tepat waktu, membuat orang lain merasa lebih rileks berada di sekitarmu.",
    "p2_label": "Kekuatan & yang Perlu Dijaga",
    "p2": "Kecerdasan dan kreativitasmu membuat orang lain sering meminta pendapatmu ketika menghadapi masalah yang rumit. Kamu juga pandai mencairkan suasana yang tegang. Namun kelincahan berpikir ini kadang membuatmu mudah bosan dan terlalu banyak mengambil peran sekaligus, sampai tidak ada satu pun yang benar-benar kamu dalami sepenuhnya. Kecenderungan untuk selalu mencari hal baru yang menantang otakmu ini bisa membuatmu kehilangan minat di tengah jalan, tepat ketika sebuah proyek sebenarnya butuh ketekunan untuk benar-benar selesai. Orang lain mungkin melihatmu sebagai sosok yang penuh ide tapi kurang tuntas dalam eksekusi.",
    "quote": "Kecerdasan akan lebih terasa hasilnya kalau difokuskan pada satu arah dalam satu waktu.",
    "p3_label": "PR Kecil Buat Kamu",
    "p3": "Coba kurangi jumlah hal yang kamu kerjakan sekaligus, dan fokuskan energi pada satu atau dua hal yang paling penting bagimu. Buat daftar prioritas sederhana di awal minggu, dan latih dirimu menahan godaan untuk memulai ide baru sebelum salah satu dari prioritas itu benar-benar selesai. Rasakan bagaimana hasil kerjamu terasa lebih dalam dan memuaskan ketika kamu benar-benar fokus, dibanding saat energimu terbagi ke banyak arah sekaligus.",
    "domains": {
        "karir": "Kreativitas dan kelincahan berpikirmu membuatmu cocok di pekerjaan yang dinamis dan penuh tantangan baru, seperti inovasi produk, konsultasi, atau peran yang butuh solusi kreatif untuk masalah yang belum pernah ditemui sebelumnya. Kamu cepat belajar hal baru dan jarang kehabisan ide segar untuk ditawarkan ke tim. Namun kecenderungan mudah bosan bisa membuatmu mengambil terlalu banyak proyek sekaligus, sehingga kualitas eksekusi jadi korban karena perhatianmu terpecah. Rekan kerja mungkin melihatmu sebagai sosok penuh ide tapi kurang bisa diandalkan untuk menyelesaikan sesuatu sampai tuntas, dan ini bisa merugikan reputasimu dalam jangka panjang. *PR: Selesaikan satu proyek yang sudah lama tertunda sebelum menerima tanggung jawab baru apa pun.*",
        "asmara": "Dalam asmara, humor dan keluwesanmu membuat hubungan terasa menyenangkan dan jarang membosankan, pasanganmu pasti sering tertawa karena caramu melihat sesuatu dari sudut pandang yang unik. Kamu juga fleksibel dan mudah menyesuaikan diri dengan kebiasaan pasangan. Namun kelincahan pikiranmu bisa membuatmu sulit benar-benar hadir secara emosional dalam momen serius, kamu cenderung mengalihkan pembicaraan berat dengan candaan, yang kadang membuat pasangan merasa perasaannya tidak ditanggapi secara serius. Kamu juga perlu waspada terhadap godaan untuk selalu mencari yang 'lebih menarik', bahkan saat hubunganmu sekarang sebenarnya sudah baik. *PR: Saat pasanganmu membicarakan sesuatu yang serius minggu ini, dengarkan tanpa membelokkannya jadi candaan.*",
        "keuangan": "Soal keuangan, kecerdikanmu membuatmu pandai melihat berbagai peluang penghasilan sekaligus, entah lewat pekerjaan utama, proyek sampingan, atau ide bisnis kreatif yang belum banyak dipikirkan orang lain. Namun kebiasaan mencoba banyak hal sekaligus bisa membuat sumber dayamu, baik waktu maupun uang, terlalu terbagi ke banyak arah tanpa ada yang benar-benar dikembangkan maksimal. Kamu juga cenderung mudah tergoda peluang baru yang terlihat menjanjikan, sampai lupa menuntaskan komitmen finansial yang sudah kamu mulai sebelumnya. *PR: Pilih satu sumber penghasilan tambahan untuk benar-benar difokuskan bulan ini, dan tunda ide-ide lain dulu.*",
        "kesehatan": "Pikiranmu yang selalu aktif dan penuh ide membuatmu jarang merasa bosan, tapi juga bisa membuat kepalamu sulit benar-benar istirahat, bahkan saat tubuhmu sedang tidak melakukan apa-apa, otakmu tetap sibuk memikirkan ide baru. Ini bisa berdampak pada kualitas tidur dan membuatmu gampang merasa gelisah tanpa sebab yang jelas. Kamu juga cenderung melompat dari satu rutinitas kesehatan ke rutinitas lain, mencoba diet atau olahraga baru sebelum benar-benar melihat hasil dari yang sebelumnya. Konsistensi kecil justru akan memberi hasil yang lebih nyata dibanding terus berganti metode. *PR: Pilih satu rutinitas kesehatan sederhana dan jalani konsisten selama dua minggu penuh tanpa berganti.*",
    },
}
