"""Konten Shio — Naga."""

NAGA_CONTENT = {
    "tagline": "🐉 Shio Naga",
    "chip": "SHIO",
    "title": "Naga — Sosok yang Sulit Diabaikan",
    "p1_label": "Siapa Kamu",
    "p1": "Dalam kepercayaan Tionghoa, shio Naga dianggap sebagai simbol keberuntungan dan kekuatan. Kamu punya aura yang membuat orang lain memperhatikanmu tanpa harus berusaha keras. Rasa percaya diri itu bukan sekadar tampilan luar, tapi tumbuh dari keyakinan bahwa kamu memang mampu mencapai hal-hal besar kalau diberi kesempatan. Sejak kecil, kamu mungkin sudah terbiasa jadi pusat perhatian, entah karena prestasi, cara bicaramu yang penuh keyakinan, atau sekadar kehadiranmu yang terasa berbeda dari orang kebanyakan. Dalam karier, energi ini membuatmu cocok mengisi peran-peran yang membutuhkan sosok yang bisa dipercaya untuk memimpin atau mewakili sebuah kelompok. Orang-orang cenderung mengingat pertemuan pertama denganmu, karena kesan yang kamu berikan biasanya cukup kuat dan sulit dilupakan begitu saja.",
    "p2_label": "Kekuatan & yang Perlu Dijaga",
    "p2": "Ambisimu jarang setengah-setengah, dan itu yang membuat orang lain mempercayakan tanggung jawab besar padamu. Sayangnya, standar tinggi yang kamu pasang untuk diri sendiri kadang ikut dibebankan ke orang lain tanpa sadar, sehingga mereka bisa merasa tertekan berada di dekatmu kalau kamu tidak sedikit melunakkan cara menyampaikannya. Rasa percaya diri yang besar ini, kalau tidak diimbangi kerendahan hati, bisa membuat orang lain merasa tidak dihargai pendapatnya, karena merasa kamu selalu yakin bahwa caramu adalah yang paling benar. Kamu juga bisa kesulitan menerima kritik, karena terbiasa menjadi sosok yang dikagumi, bukan yang dikoreksi.",
    "quote": "Kekuatan yang sesungguhnya terlihat justru saat kamu memilih untuk lebih lembut.",
    "p3_label": "PR Kecil Buat Kamu",
    "p3": 'Coba luangkan waktu untuk memuji usaha orang lain sebelum menunjukkan apa yang masih kurang. Kebiasaan kecil ini akan membuat orang-orang di sekitarmu merasa dihargai, bukan cuma dinilai dari hasil akhirnya saja. Latih juga dirimu menerima satu kritik kecil tanpa langsung membela diri, dengan cara mendengarkan sampai selesai dan bertanya "apa maksudnya lebih lanjut?" sebelum menanggapi. Kebiasaan ini akan membuat orang lain lebih berani jujur denganmu di masa depan.',
    "domains": {
        "karir": "Ambisi dan auramu yang kuat membuatmu cocok mengisi posisi kepemimpinan atau peran yang membutuhkan sosok yang bisa dipercaya untuk mewakili sebuah tim. Kamu punya visi besar dan berani mengejarnya tanpa setengah-setengah, dan itu sering membuat orang lain terinspirasi ikut bekerja lebih keras di dekatmu. Namun standar tinggi yang kamu pasang untuk dirimu sendiri bisa membuatmu tidak sabar dengan rekan kerja yang lebih lambat atau punya cara kerja berbeda, sehingga kamu berisiko dianggap terlalu dominan atau sulit diajak kompromi. Kamu juga perlu waspada terhadap kebiasaan sulit menerima kritik dari atasan atau rekan kerja, karena terbiasa jadi sosok yang dikagumi, bukan yang dikoreksi. *PR: Minta satu masukan jujur dari rekan kerja soal caramu memimpin, lalu dengarkan sampai selesai tanpa membela diri.*",
        "asmara": "Dalam asmara, karismamu membuatmu jarang kesulitan menarik perhatian, dan pasanganmu biasanya bangga berada di sisimu karena kehadiranmu yang penuh percaya diri. Kamu juga tipe yang berani berkomitmen kalau sudah yakin, tidak setengah-setengah dalam mencintai. Tapi standar tinggi yang kamu terapkan ke diri sendiri bisa ikut kamu bebankan ke pasangan tanpa sadar, membuatnya merasa harus terus membuktikan diri layak bersamamu. Kamu juga bisa kesulitan meminta maaf lebih dulu saat berselisih, karena merasa mengalah sama dengan kalah, padahal dalam hubungan yang sehat, siapa yang meminta maaf lebih dulu bukan soal menang atau kalah. *PR: Coba jadi yang pertama meminta maaf di perselisihan kecil berikutnya, meski menurutmu kamu tidak sepenuhnya salah.*",
        "keuangan": "Soal keuangan, ambisimu membuatmu berani menargetkan hasil besar dan biasanya kamu punya rencana jangka panjang yang jelas untuk mencapainya, entah lewat karier, bisnis, atau investasi. Kamu tidak puas dengan hasil yang biasa-biasa saja, dan dorongan ini sering membuahkan hasil finansial yang lebih baik dibanding kebanyakan orang. Namun ambisi yang terlalu besar bisa membuatmu mengambil risiko finansial yang sebenarnya di luar kemampuanmu, hanya demi gengsi atau ingin terlihat sukses di mata orang lain. Kamu juga perlu waspada terhadap gaya hidup yang mengikuti citra diri yang ingin kamu tunjukkan, sampai pengeluaran untuk penampilan melebihi kebutuhan yang sebenarnya. *PR: Evaluasi satu pengeluaran besar bulan ini, apakah itu benar-benar kebutuhan atau sekadar menjaga gengsi.*",
        "kesehatan": "Energi dan rasa percaya dirimu biasanya membuatmu tampak selalu bugar dan penuh semangat di mata orang lain. Kamu jarang mau terlihat lemah, dan ini bisa membuatmu memaksakan diri tetap tampil prima meski sebenarnya tubuhmu sedang butuh istirahat. Kebiasaan menahan diri untuk tidak terlihat rapuh ini berisiko membuatmu menunda pergi ke dokter atau mengakui saat sesuatu terasa tidak beres, sampai masalahnya jadi lebih besar dari seharusnya. Kamu juga perlu belajar bahwa mengakui butuh bantuan atau istirahat bukan tanda kelemahan, justru bagian dari menjaga kekuatan yang selama ini jadi identitas dirimu. *PR: Kalau ada keluhan fisik yang kamu abaikan minggu-minggu ini, coba periksakan diri sekarang, jangan ditunda lagi.*",
    },
}
