"""Konten Shio — Tikus."""

TIKUS_CONTENT = {
    "tagline": "🐭 Shio Tikus",
    "chip": "SHIO",
    "title": "Tikus — Si Cerdik yang Serba Bisa",
    "p1_label": "Siapa Kamu",
    "p1": "Dalam kepercayaan Tionghoa, shio Tikus dikenal sebagai simbol kecerdikan dan kelincahan berpikir. Kamu punya kemampuan membaca situasi dengan cepat dan menemukan jalan keluar di saat orang lain masih kebingungan. Naluri bertahan hidupmu kuat, dan kamu jarang benar-benar kehabisan akal meski berada dalam keadaan sulit. Kecerdikan ini biasanya sudah kelihatan sejak kamu masih kecil, misalnya lewat kebiasaan mencari cara paling efisien untuk menyelesaikan tugas, bukan sekadar cara yang paling umum dilakukan orang lain. Di lingkungan kerja, kamu sering jadi orang yang dicari saat tim menghadapi masalah mendadak, karena kamu bisa berpikir cepat sambil tetap tenang. Dalam pergaulan, kelincahan berpikirmu membuatmu mudah menyesuaikan diri di berbagai kelompok, dari obrolan santai sampai diskusi yang serius sekalipun.",
    "p2_label": "Kekuatan & yang Perlu Dijaga",
    "p2": "Kecerdikan dan kepekaanmu terhadap peluang membuat orang lain sering meminta pendapatmu sebelum mengambil keputusan penting. Kamu juga cepat beradaptasi dengan keadaan baru. Namun kelincahan berpikir ini terkadang membuatmu terlalu berhati-hati atau curiga berlebihan, sampai sulit benar-benar percaya penuh pada orang lain. Kewaspadaan yang berlebihan ini bisa membuatmu menganalisis motif orang lain secara berlebihan, bahkan pada niat baik yang sebenarnya tulus, sehingga hubungan yang seharusnya bisa lebih dekat justru berhenti di permukaan saja. Kamu juga bisa terlalu sibuk memikirkan rencana cadangan, sampai lupa menikmati momen yang sedang berjalan.",
    "quote": "Kecerdikan akan membawamu jauh, tapi kepercayaan yang tulus akan membawamu lebih jauh lagi.",
    "p3_label": "PR Kecil Buat Kamu",
    "p3": "Coba beri satu orang yang selama ini kamu ragukan kesempatan untuk membuktikan dirinya, tanpa langsung menilai dari kecurigaanmu. Mulailah dengan langkah kecil, misalnya mempercayakan satu tugas sederhana kepada orang tersebut dan melihat bagaimana hasilnya, sebelum menyimpulkan apa pun tentang niatnya. Latihan kecil ini akan membantumu membedakan mana kewaspadaan yang benar-benar dibutuhkan, dan mana yang sebenarnya hanya kebiasaan lama yang sudah tidak relevan lagi.",
    "domains": {
        "karir": "Di dunia kerja, kecerdikanmu adalah aset yang jarang dimiliki orang lain secara alami. Kamu bisa melihat celah atau peluang di tempat yang orang lain anggap jalan buntu, dan itu membuatmu cocok di peran yang menuntut solusi cepat atau negosiasi yang lihai, seperti business development, marketing, atau posisi yang butuh membaca situasi pasar dengan gesit. Atasan biasanya menghargaimu karena kamu jarang kehabisan ide saat menghadapi masalah mendadak. Tantangannya, kewaspadaan berlebihmu bisa membuatmu ragu mendelegasikan tugas, karena merasa orang lain tidak akan mengerjakannya seteliti dirimu, dan ini bisa membuatmu kelebihan beban kerja tanpa disadari. Kamu juga perlu hati-hati agar kecerdikan tidak berubah jadi terlalu banyak jalan pintas yang mengorbankan kualitas jangka panjang demi hasil instan. *PR: Latih delegasi satu tugas kecil ke rekan kerja minggu ini, dan biarkan dia menyelesaikannya dengan caranya sendiri.*",
        "asmara": "Dalam hubungan asmara, kamu cenderung mengamati dulu sebelum benar-benar membuka hati, karena naluri waspadamu juga bekerja di ranah perasaan. Kamu ingin memastikan pasanganmu benar-benar tulus sebelum kamu berinvestasi penuh secara emosional, dan proses ini kadang membuat pasangan merasa harus membuktikan diri berulang-ulang. Kecerdikanmu juga bisa membuatmu pandai membaca sinyal dari pasangan, seperti tahu kapan dia sedang tidak baik-baik saja meski dia tidak bilang apa-apa. Namun kalau kewaspadaan ini kebablasan, kamu bisa terus mencurigai motif pasangan bahkan saat tidak ada tanda-tanda yang mencurigakan, dan itu bisa melelahkan hubungan dalam jangka panjang. Kepercayaan yang kamu bangun pelan-pelan justru akan jauh lebih kuat kalau kamu berani memberi ruang tanpa terus menguji. *PR: Sekali ini, coba percaya penuh pada kata-kata pasanganmu tanpa mencari bukti tambahan.*",
        "keuangan": "Soal keuangan, kecerdikanmu membuatmu jago melihat peluang yang orang lain lewatkan, entah itu diskon tersembunyi, cara menghemat, atau peluang usaha sampingan yang belum banyak dilirik orang. Kamu juga cenderung punya rencana cadangan untuk keuanganmu, tidak suka mengandalkan satu sumber penghasilan saja. Sisi ini membuatmu relatif aman secara finansial dibanding kebanyakan orang. Tapi kewaspadaan berlebih bisa membuatmu terlalu banyak menimbun uang untuk skenario terburuk yang belum tentu terjadi, sampai jarang menikmati hasil kerja kerasmu sendiri. Kamu juga perlu waspada terhadap kebiasaan menghitung untung-rugi secara berlebihan dalam hal-hal kecil, yang justru menghabiskan energi mental lebih banyak dari nilai uang yang dihemat. *PR: Alokasikan satu pos kecil bulan ini khusus untuk menikmati sesuatu tanpa rasa bersalah.*",
        "kesehatan": "Otakmu yang selalu aktif berpikir dan menganalisis bisa jadi pedang bermata dua untuk kesehatanmu. Di satu sisi, kewaspadaanmu membuatmu cepat sadar kalau ada yang tidak beres dengan tubuhmu dan segera mencari solusi. Di sisi lain, pikiran yang terus bekerja bahkan saat seharusnya istirahat bisa membuatmu susah tidur nyenyak atau gampang merasa cemas tanpa sebab yang jelas. Kamu tipe yang sering memikirkan banyak kemungkinan sekaligus, termasuk soal kesehatan, sehingga gejala kecil bisa terasa lebih menakutkan di kepalamu daripada kenyataannya. Penting untukmu punya rutinitas yang benar-benar mematikan mode 'berpikir' itu, entah lewat olahraga ringan, journaling, atau sekadar diam tanpa gadget beberapa menit sehari. *PR: Coba teknik napas dalam 5 menit sebelum tidur, tanpa memikirkan rencana besok.*",
    },
}
