"""Konten Shio — Ular."""

ULAR_CONTENT = {
    "tagline": "🐍 Shio Ular",
    "chip": "SHIO",
    "title": "Ular — Pemikir Tajam yang Penuh Intuisi",
    "p1_label": "Siapa Kamu",
    "p1": "Shio Ular melambangkan kebijaksanaan, ketenangan, dan intuisi yang tajam. Kamu jarang bertindak tanpa perhitungan, dan lebih suka mengamati situasi dengan saksama sebelum mengambil langkah. Ketenangan luarmu sering membuat orang salah sangka bahwa kamu tidak peduli, padahal di dalam kamu sedang memikirkan segalanya dengan sangat detail. Kamu punya kebiasaan mengamati orang lain sebelum benar-benar terbuka, dan biasanya butuh waktu cukup lama sebelum kamu benar-benar mempercayai seseorang sepenuhnya. Dalam pekerjaan, ketajaman analisismu membuatmu unggul dalam melihat pola atau risiko yang belum disadari orang lain, sehingga kamu sering jadi orang yang diandalkan untuk memikirkan strategi jangka panjang. Kamu juga cenderung nyaman menghabiskan waktu sendiri untuk merenung, dan tidak selalu butuh keramaian untuk merasa baik-baik saja.",
    "p2_label": "Kekuatan & yang Perlu Dijaga",
    "p2": "Ketajaman berpikir dan intuisimu membuatmu jarang terkecoh oleh hal-hal yang terlihat di permukaan. Kamu juga bisa tetap tenang dalam situasi yang membuat orang lain panik. Namun kecenderungan untuk menyimpan pemikiran sendiri ini kadang membuat orang lain kesulitan menebak apa yang sebenarnya kamu rasakan atau inginkan. Kebiasaan menjaga jarak emosional ini bisa membuat hubungan dekatmu terasa dingin di mata orang lain, meski sebenarnya kamu peduli. Orang-orang di sekitarmu mungkin sering merasa tidak yakin apakah mereka benar-benar dekat denganmu, karena kamu jarang membagikan apa yang sebenarnya ada di pikiranmu.",
    "quote": "Ketenangan yang bijak akan lebih bermakna kalau sesekali dibagikan, bukan hanya disimpan sendiri.",
    "p3_label": "PR Kecil Buat Kamu",
    "p3": "Coba sampaikan satu pemikiran atau analisismu secara terbuka kepada orang terdekat, alih-alih hanya memendamnya dalam kepala. Mulailah dari topik yang terasa aman, misalnya pendapatmu tentang sesuatu yang sedang terjadi, sebelum melangkah ke perasaan yang lebih personal. Ingat bahwa keterbukaan sedikit demi sedikit tidak akan mengurangi ketenanganmu, justru bisa membuat orang lain merasa lebih dekat dan dipercaya olehmu.",
    "domains": {
        "karir": "Ketajaman analisismu adalah senjata utama di dunia kerja, kamu bisa melihat risiko atau pola yang belum disadari orang lain jauh sebelum masalah itu benar-benar muncul. Ini membuatmu cocok di peran strategi, riset, atau posisi yang butuh pemikiran jangka panjang dan ketenangan dalam mengambil keputusan. Rekan kerja mungkin sulit menebak isi kepalamu, tapi mereka tahu keputusanmu biasanya sudah dipikirkan matang-matang. Tantangannya, kebiasaan menyimpan pemikiran sendiri bisa membuat tim kesulitan memahami arah pikiranmu, sehingga kolaborasi terasa kurang lancar meski idemu sebenarnya bagus. Kamu juga cenderung kurang vokal mempromosikan pencapaianmu sendiri, sampai kontribusimu kurang terlihat dibanding rekan yang lebih terbuka. *PR: Bagikan satu insight atau analisismu secara terbuka di rapat tim minggu ini, bukan hanya menyimpannya sendiri.*",
        "asmara": "Dalam asmara, intuisimu yang tajam membuatmu jarang salah menilai karakter pasangan, kamu bisa merasakan ketulusan atau kepura-puraan seseorang jauh sebelum orang lain menyadarinya. Kamu juga tipe yang setia sekali sudah berkomitmen, meski butuh waktu lama untuk sampai ke titik itu. Namun kebiasaan menjaga jarak emosional bisa membuat pasangan merasa tidak pernah benar-benar mengenalmu sepenuhnya, meski sudah lama bersama. Ketenangan luarmu yang jarang menunjukkan emosi juga bisa disalahartikan sebagai ketidakpedulian, padahal kamu sebenarnya sangat memperhatikan dari dalam. Pasangan butuh sesekali melihat sisi rentanmu untuk merasa benar-benar dekat. *PR: Ceritakan satu perasaan yang biasanya kamu simpan sendiri kepada pasanganmu minggu ini.*",
        "keuangan": "Soal keuangan, ketajaman analisismu membuatmu jago membaca peluang dan risiko sebelum mengambil keputusan finansial, kamu jarang tergoda investasi yang terlihat menggiurkan di permukaan tapi sebenarnya berisiko tinggi. Kamu lebih suka riset mendalam dulu sebelum benar-benar menaruh uang di sesuatu. Namun kehati-hatian ini kadang berubah jadi terlalu banyak analisis sampai kehilangan momentum, peluang bagus yang sebenarnya sudah cukup jelas bisa terlewat karena kamu masih terus mempertimbangkan. Kamu juga cenderung tidak membicarakan rencana keuangan dengan orang terdekat, padahal masukan dari sudut pandang lain kadang membantu melengkapi analisismu sendiri. *PR: Diskusikan satu rencana finansialmu dengan orang yang kamu percaya minggu ini.*",
        "kesehatan": "Ketenanganmu secara alami adalah modal besar untuk kesehatan mental, kamu jarang panik berlebihan menghadapi tekanan. Namun kebiasaan memendam segala sesuatu di dalam kepala tanpa membaginya bisa jadi beban tersembunyi yang lama-lama menumpuk jadi stres kronis, meski dari luar kamu terlihat baik-baik saja. Kamu juga cenderung lebih nyaman menyendiri untuk memulihkan energi, yang sebenarnya sehat, tapi perlu diimbangi dengan interaksi sosial yang cukup supaya tidak terlalu terisolasi. Sesekali pikiranmu yang terus bekerja menganalisis segala hal juga bisa membuatmu susah benar-benar rileks, bahkan saat sedang beristirahat. *PR: Coba lakukan satu aktivitas fisik yang membuat pikiranmu benar-benar berhenti menganalisis, seperti jalan kaki tanpa tujuan.*",
    },
}
