"""Konten Weton — Kliwon."""

KLIWON_CONTENT = {
    "tagline": "☾ Pasaran Kliwon",
    "chip": "WETON",
    "title": "{hari} Kliwon — Neptu {neptu}, Sosok yang Penuh Kepekaan",
    "p1_label": "Siapa Kamu",
    "p1": "Menurut primbon Jawa, kamu lahir dengan pasaran Kliwon, yang jatuh pada hari {hari} dengan neptu total {neptu}. Pasaran Kliwon sering dikaitkan dengan kepekaan batin yang dalam dan kemampuan merasakan hal-hal yang tidak terucap oleh orang lain. Kamu punya intuisi yang tajam, dan sering kali firasatmu tentang sesuatu ternyata benar. Kepekaan ini membuatmu sering jadi orang pertama yang menyadari kalau ada yang tidak beres dengan seseorang, bahkan sebelum orang itu sendiri mengucapkannya. Dalam hubungan sosial, kamu punya sisi spiritual dan reflektif yang membuatmu tertarik memahami hal-hal yang lebih dalam dari sekadar permukaan, seperti makna di balik peristiwa atau pola yang berulang dalam hidup. Banyak orang merasa nyaman berbagi cerita denganmu, karena kamu punya cara memahami situasi tanpa perlu penjelasan panjang lebar.",
    "p2_label": "Kekuatan & yang Perlu Dijaga",
    "p2": "Kepekaan dan intuisimu membuatmu mudah memahami situasi maupun perasaan orang lain tanpa perlu penjelasan panjang. Kamu juga punya sisi spiritual yang membuatmu tenang menghadapi ketidakpastian. Namun kepekaan yang besar ini kadang membuatmu mudah menyerap energi negatif dari sekitarmu, sehingga suasana hatimu jadi mudah terpengaruh oleh keadaan orang lain. Kalau tidak dijaga, kepekaan ini bisa membuatmu kelelahan secara emosional tanpa penyebab yang jelas, terutama setelah berada lama di lingkungan yang penuh tekanan atau konflik. Kamu juga rentan menyerap kekhawatiran orang lain seolah itu kekhawatiranmu sendiri, sampai sulit membedakan mana perasaan yang benar-benar milikmu.",
    "quote": "Kepekaan itu anugerah, tapi kamu juga berhak menjaga jarak dari energi yang tidak membuatmu nyaman.",
    "p3_label": "PR Kecil Buat Kamu",
    "p3": "Ketika merasa energimu terkuras oleh suasana atau orang lain, coba luangkan waktu sendiri sejenak untuk memulihkan diri sebelum melanjutkan aktivitas. Buat kebiasaan kecil untuk mengecek kondisi emosimu di penghujung hari, dan tanyakan pada diri sendiri mana perasaan yang benar-benar milikmu, dan mana yang mungkin kamu serap dari orang lain. Menetapkan batasan yang sehat, misalnya membatasi waktu bersama orang yang energinya terasa berat, juga akan membantu kepekaanmu tetap jadi kekuatan, bukan beban.",
    "domains": {
        "karir": "Intuisimu yang tajam membuatmu unggul di pekerjaan yang butuh kepekaan membaca situasi atau orang, seperti konseling, HR, riset pasar, atau peran apa pun yang mengharuskan kamu memahami kebutuhan orang lain lebih dari yang mereka ucapkan. Rekan kerja sering merasa kamu 'mengerti' masalah mereka lebih cepat dari yang mereka jelaskan sendiri. Namun kepekaan ini bisa membuatmu mudah menyerap tekanan dari lingkungan kerja yang penuh konflik atau kompetisi, dan itu bisa menguras energimu lebih cepat dibanding rekan lain yang tidak sesensitif dirimu. *PR: Setelah rapat atau interaksi kerja yang berat minggu ini, beri diri lima menit untuk 'melepaskan' energi itu sebelum lanjut ke tugas berikutnya.*",
        "asmara": "Dalam hubungan, kepekaanmu membuatmu bisa merasakan perubahan suasana hati pasangan bahkan sebelum diucapkan, dan ini membuat pasangan merasa benar-benar dipahami. Kamu juga punya kedalaman emosional yang membuat hubunganmu terasa bermakna, bukan sekadar permukaan. Namun kepekaan yang besar ini bisa membuatmu terlalu mudah menyerap kecemasan atau masalah pasangan sebagai bebanmu sendiri, sampai sulit membedakan mana emosimu dan mana emosinya. Kamu perlu menjaga batasan emosional yang sehat supaya empati tidak berubah jadi kelelahan. *PR: Ketika pasanganmu sedang emosi minggu ini, coba dampingi tanpa sepenuhnya ikut larut dalam perasaan itu.*",
        "keuangan": "Soal keuangan, intuisimu kadang membantumu merasakan peluang atau risiko yang belum tentu terlihat jelas secara data, semacam firasat yang sering terbukti benar. Namun kepekaan emosionalmu bisa membuat keputusan finansialmu mudah terpengaruh suasana hati, kamu bisa berbelanja lebih banyak saat sedang sedih untuk menghibur diri, atau menahan diri berlebihan saat sedang cemas tanpa alasan finansial yang jelas. Penting untukmu punya sistem yang tidak bergantung pada mood harian dalam mengatur uang. *PR: Buat anggaran tetap bulanan yang tidak berubah mengikuti suasana hatimu, dan patuhi itu minggu ini.*",
        "kesehatan": "Kepekaanmu terhadap energi sekitar membuatmu rentan menyerap stres orang lain sebagai stresmu sendiri, ini bisa berdampak nyata ke kesehatan fisik seperti gangguan tidur, sakit kepala, atau kelelahan yang datang tanpa sebab jelas. Kamu butuh ritual pemulihan yang konsisten untuk 'membersihkan' energi yang kamu serap sepanjang hari, entah lewat meditasi, journaling, atau sekadar waktu sendiri dalam diam. Mengabaikan kebutuhan ini dalam jangka panjang bisa membuat kepekaanmu yang sebenarnya adalah kekuatan justru jadi sumber kelelahan kronis. *PR: Lakukan satu ritual 'membersihkan energi' sederhana setiap malam minggu ini, meski hanya lima menit.*",
    },
}
