"""Konten Weton — Legi."""

LEGI_CONTENT = {
    "tagline": "☾ Pasaran Legi",
    "chip": "WETON",
    "title": "{hari} Legi — Neptu {neptu}, Pembawa Ketenangan",
    "p1_label": "Siapa Kamu",
    "p1": "Menurut primbon Jawa, kamu lahir dengan pasaran Legi, yang jatuh pada hari {hari} dengan neptu total {neptu}. Pasaran Legi sering dikaitkan dengan sosok yang membawa ketenangan bagi lingkungan sekitarnya, tempat orang lain merasa nyaman bercerita dan meminta pendapat. Kehadiranmu cenderung meredakan suasana yang tegang, bukan memperkeruhnya. Dalam banyak kasus, kamu jadi tempat teman-teman atau keluarga singgah dulu sebelum mereka mengambil keputusan besar, karena cara bicaramu yang tenang membuat mereka merasa lebih jernih memikirkan masalahnya sendiri. Di lingkungan kerja, sifat ini membuatmu sering dipercaya memegang peran yang butuh kesabaran tinggi, seperti menengahi konflik antar rekan atau menjaga hubungan baik dengan klien yang sensitif. Di rumah pun, kamu biasanya jadi sosok yang menjaga suasana tetap adem, bahkan ketika anggota keluarga lain sedang emosi.",
    "p2_label": "Kekuatan & yang Perlu Dijaga",
    "p2": "Kepekaanmu terhadap perasaan orang lain adalah kekuatan besar yang tidak semua orang punya. Namun karena terlalu sering memikirkan perasaan orang lain, kamu kadang menunda kepentinganmu sendiri, dan itu bisa membuatmu kelelahan tanpa disadari oleh orang di sekelilingmu. Kekuatan ini juga membuatmu jadi pendengar yang baik dalam hubungan dekat, karena kamu jarang buru-buru memberi nasihat sebelum benar-benar memahami apa yang sedang dirasakan lawan bicaramu. Sayangnya, karena terbiasa jadi pihak yang mengalah demi ketenangan bersama, kamu bisa jatuh ke pola di mana orang lain terbiasa mengandalkanmu tanpa pernah balik bertanya bagaimana kabarmu. Lama-lama, beban emosional yang kamu tampung sendirian ini bisa menumpuk tanpa kamu sadari, sampai suatu saat meledak dalam bentuk kelelahan mental atau rasa kesepian, meski kamu dikelilingi banyak orang yang menyayangimu.",
    "quote": "Menjaga perasaan orang lain itu baik, asal tidak sampai melupakan perasaanmu sendiri.",
    "p3_label": "PR Kecil Buat Kamu",
    "p3": "Sesekali, latih diri untuk mengatakan apa yang sebenarnya kamu butuhkan, bukan hanya apa yang membuat orang lain nyaman. Orang-orang terdekatmu justru akan lebih menghargai kejujuran itu. Cobalah mulai dari hal kecil, misalnya memberi tahu temanmu kalau kamu sedang lelah dan butuh waktu sendiri, alih-alih tetap menemani mereka sampai kamu benar-benar kehabisan energi. Kamu juga bisa membuat kebiasaan sederhana: setiap kali selesai menenangkan orang lain, tanyakan pada dirimu sendiri satu hal yang kamu butuhkan saat itu juga, lalu penuhi, sekecil apa pun itu.",
    "domains": {
        "karir": "Ketenanganmu adalah aset berharga di dunia kerja, kamu cocok di peran yang butuh kesabaran ekstra, seperti customer service, mediasi, HR, atau posisi apa pun yang mengharuskan menjaga hubungan baik dengan banyak pihak sekaligus. Rekan kerja merasa aman berdiskusi denganmu karena kamu jarang bereaksi berlebihan meski situasinya sedang tegang. Namun kebiasaan mendahulukan ketenangan tim di atas kepentinganmu sendiri bisa membuatmu jadi tempat sampah keluhan tanpa penghargaan yang seimbang, dan kamu jarang mengajukan diri untuk hal-hal yang sebenarnya jadi hakmu, seperti promosi atau pengakuan atas jasamu meredam banyak konflik di belakang layar. *PR: Sampaikan satu pencapaianmu yang selama ini kamu diamkan ke atasan minggu ini.*",
        "asmara": "Dalam hubungan, ketenanganmu membuat pasangan merasa punya tempat berlabuh yang aman, kamu jarang membuat drama dan selalu berusaha memahami sudut pandangnya lebih dulu sebelum bereaksi. Ini membuat hubunganmu terasa stabil dan nyaman dalam jangka panjang. Namun kebiasaan mengalah demi menjaga kedamaian bisa membuat kebutuhan emosionalmu sendiri jarang tersampaikan, sampai pasangan tidak benar-benar tahu apa yang membuatmu bahagia atau kecewa. Lama-lama, ini bisa membuatmu merasa sendirian meski berada dalam hubungan, karena kamu selalu jadi yang memberi ruang, jarang menerima. *PR: Ceritakan satu hal yang kamu butuhkan dari pasanganmu minggu ini, tanpa dibungkus permintaan maaf.*",
        "keuangan": "Soal keuangan, sifat tenangmu membuatmu jarang mengambil keputusan finansial yang gegabah, kamu lebih suka mempertimbangkan matang-matang sebelum mengeluarkan uang untuk sesuatu yang besar. Kamu juga cenderung dermawan pada keluarga atau teman yang sedang kesulitan. Namun kebiasaan mendahulukan kebutuhan orang lain bisa membuat rencana keuanganmu sendiri sering tertunda, kamu lebih siap membantu orang lain daripada menabung untuk tujuanmu sendiri. Penting untukmu belajar bahwa menjaga kondisi finansialmu sendiri tetap sehat bukan berarti kamu pelit atau tidak peduli pada orang lain. *PR: Sisihkan dana untuk tujuan finansialmu sendiri sebelum membantu orang lain bulan ini, bukan sesudahnya.*",
        "kesehatan": "Karena kamu terbiasa jadi tempat orang lain berkeluh kesah, tanpa sadar kamu menyerap banyak beban emosional yang sebenarnya bukan milikmu. Ini bisa menumpuk jadi kelelahan mental yang tidak terlihat dari luar, karena kamu tetap tampak tenang meski di dalam sedang penuh. Kamu perlu punya ruang khusus untuk melepaskan beban itu, bukan sekadar menampungnya terus-menerus. Kesehatan fisikmu juga bisa terdampak kalau kelelahan emosional ini dibiarkan, misalnya lewat gangguan tidur atau energi yang cepat habis meski aktivitas fisikmu tidak berat. *PR: Cari satu orang atau cara untuk 'curhat balik' minggu ini, bukan hanya jadi pendengar seperti biasanya.*",
    },
}
