"""Konten Weton — Pahing."""

PAHING_CONTENT = {
    "tagline": "☾ Pasaran Pahing",
    "chip": "WETON",
    "title": "{hari} Pahing — Neptu {neptu}, Sosok yang Bersemangat",
    "p1_label": "Siapa Kamu",
    "p1": "Menurut primbon Jawa, kamu lahir dengan pasaran Pahing, yang jatuh pada hari {hari} dengan neptu total {neptu}. Pasaran Pahing identik dengan semangat yang menyala dan keinginan kuat untuk selalu tampil terbaik. Kamu punya energi yang membuatmu tidak puas hanya berdiam di tempat, dan selalu mendorong diri sendiri untuk berkembang. Energi ini biasanya sudah terlihat sejak kamu masih muda, misalnya lewat kebiasaan ingin selalu jadi yang terdepan di sekolah, organisasi, atau lingkungan pertemanan. Dalam pekerjaan, kamu jarang betah di posisi yang terasa monoton dan datar-datar saja; kamu selalu mencari tantangan baru yang bisa membuktikan kemampuanmu. Di mata orang lain, kamu terlihat sebagai sosok yang bersemangat menular, tipe orang yang begitu masuk ruangan langsung mengubah suasana jadi lebih hidup dan penuh energi.",
    "p2_label": "Kekuatan & yang Perlu Dijaga",
    "p2": "Semangat dan ambisimu membuat orang lain melihatmu sebagai sosok yang pantang menyerah dalam mengejar sesuatu. Kamu juga cenderung berani mengambil risiko demi hasil yang lebih besar. Namun semangat yang menggebu ini kadang membuatmu kurang sabar terhadap orang lain yang bergerak lebih lambat, atau terhadap proses yang belum menunjukkan hasil secepat yang kamu harapkan. Kekuatan ambisimu juga bisa membuatmu terlalu keras menilai dirimu sendiri ketika sesuatu tidak berjalan sesuai rencana, seolah setiap hambatan kecil adalah tanda kegagalan besar. Di lingkungan tim, semangat besarmu kadang membuat rekan kerja merasa terburu-buru atau tertekan mengikuti kecepatanmu, padahal mereka mungkin punya cara kerja yang berbeda namun sama efektifnya.",
    "quote": "Semangat besar akan lebih membawa hasil kalau disertai kesabaran menunggu waktu yang tepat.",
    "p3_label": "PR Kecil Buat Kamu",
    "p3": "Coba beri ruang pada orang lain untuk bergerak dengan kecepatan mereka sendiri, tanpa terburu-buru mendorong mereka menyamai temponu. Ketika bekerja sama dalam tim, cobalah bertanya dulu kepada rekanmu tentang kecepatan yang nyaman buat mereka, sebelum menetapkan target yang sebenarnya cuma nyaman buatmu sendiri. Latih juga kesabaran dengan memberi jeda satu atau dua hari sebelum menilai sebuah rencana sebagai gagal, karena hasil besar kadang memang butuh waktu lebih lama dari yang kamu harapkan.",
    "domains": {
        "karir": "Ambisimu yang besar membuatmu cocok mengejar posisi kepemimpinan atau peran yang menuntut hasil nyata dan terukur, seperti target sales, manajemen proyek, atau wirausaha. Kamu tidak takut kerja keras demi mencapai apa yang kamu inginkan, dan semangat ini sering membuatmu naik jabatan lebih cepat dari rekan seangkatan. Namun ketidaksabaranmu bisa membuatmu terburu-buru mengambil keputusan penting sebelum semua data terkumpul, dan kekecewaan terhadap hasil yang belum maksimal bisa membuatmu terlalu keras menilai kinerja diri sendiri maupun tim. *PR: Beri tim atau proyekmu jeda satu minggu tambahan sebelum menilai hasilnya sebagai kurang memuaskan.*",
        "asmara": "Dalam hubungan, energimu yang menggebu membuat hubungan terasa hidup dan penuh semangat, kamu tidak suka hubungan yang terasa datar dan selalu ingin mengajak pasangan berkembang bersama. Namun ketidaksabaranmu bisa membuatmu cepat kecewa kalau pasangan tidak bergerak secepat yang kamu harapkan, entah dalam mengambil keputusan bersama atau menyelesaikan masalah. Kamu perlu belajar bahwa ritme setiap orang berbeda, dan memaksakan kecepatanmu justru bisa membuat pasangan merasa tertekan dan kurang dihargai prosesnya sendiri. *PR: Tanyakan ke pasanganmu ritme yang nyaman buatnya dalam mengambil keputusan bersama, dan hormati itu minggu ini.*",
        "keuangan": "Soal keuangan, semangat dan ambisimu membuatmu berani mengejar penghasilan lebih besar, entah lewat kerja keras ekstra, usaha sampingan, atau investasi yang agresif. Kamu jarang puas dengan hasil yang biasa-biasa saja. Namun ketidaksabaran untuk cepat melihat hasil bisa membuatmu tergoda mengambil keputusan finansial berisiko tinggi tanpa riset yang cukup, hanya karena ingin cepat kaya atau cepat melihat pertumbuhan. Kesabaran dalam membangun kekayaan justru sering jadi kunci yang lebih penting dari kecepatan semata. *PR: Sebelum mengambil peluang investasi baru, riset dulu selama satu minggu penuh tanpa terburu-buru memutuskan.*",
        "kesehatan": "Energimu yang tinggi membuatmu jarang lelah secara fisik, tapi ambisi yang terus mendorongmu bergerak bisa membuatmu lupa memberi tubuh waktu istirahat yang cukup. Kamu tipe yang sulit berhenti sebelum target tercapai, bahkan kalau itu berarti mengorbankan jam tidur atau pola makan yang teratur. Tekanan yang kamu ciptakan sendiri demi mengejar hasil terbaik juga bisa memicu stres yang berdampak ke kesehatan jangka panjang kalau tidak diimbangi jeda yang cukup. *PR: Tetapkan satu waktu istirahat wajib setiap hari minggu ini, yang tidak bisa digeser apa pun alasannya.*",
    },
}
