"""Konten Weton — Pon."""

PON_CONTENT = {
    "tagline": "☾ Pasaran Pon",
    "chip": "WETON",
    "title": "{hari} Pon — Neptu {neptu}, Penengah yang Bijaksana",
    "p1_label": "Siapa Kamu",
    "p1": "Menurut primbon Jawa, kamu lahir dengan pasaran Pon, yang jatuh pada hari {hari} dengan neptu total {neptu}. Pasaran Pon sering dikaitkan dengan sosok yang bijaksana dan pandai menjaga keseimbangan dalam hubungan dengan orang lain. Kamu cenderung berpikir matang sebelum bertindak, dan jarang membuat keputusan yang terburu-buru. Dalam pertemanan atau keluarga, kamu biasanya jadi sosok yang paling sering diminta pendapat ketika ada perselisihan, karena cara pandangmu terasa netral dan tidak memihak salah satu sisi secara membabi buta. Di tempat kerja, kemampuan ini membuatmu cocok mengisi peran yang butuh diplomasi, seperti menjembatani kepentingan antar divisi atau menjaga hubungan baik antara atasan dan bawahan. Kamu juga cenderung lebih tenang menghadapi tekanan dibanding kebanyakan orang di sekitarmu.",
    "p2_label": "Kekuatan & yang Perlu Dijaga",
    "p2": "Kebijaksanaan dan kemampuanmu menjaga keharmonisan membuat orang lain sering menjadikanmu penengah saat ada perbedaan pendapat. Kamu juga dipercaya karena pertimbanganmu yang matang. Namun kehati-hatian ini kadang membuatmu terlalu lama menimbang-nimbang, sampai kesempatan yang seharusnya bisa kamu ambil justru terlewatkan. Kebiasaan mempertimbangkan semua sisi ini juga bisa membuatmu tampak kurang tegas di mata orang lain, terutama saat situasi menuntut keputusan cepat tanpa banyak basa-basi. Ada kalanya, keinginan untuk selalu adil bagi semua pihak justru membuatmu sendiri berada di posisi yang serba salah, karena tidak ada keputusan yang bisa memuaskan semua orang sekaligus.",
    "quote": "Pertimbangan yang matang itu penting, tapi ada kalanya keberanian mengambil keputusan lebih berarti dari kesempurnaan pertimbangan itu sendiri.",
    "p3_label": "PR Kecil Buat Kamu",
    "p3": 'Ketika dihadapkan pada satu keputusan kecil, coba beri batas waktu untuk menimbang, lalu putuskan sebelum batas waktu itu habis, alih-alih terus menunda. Latihan ini bisa dimulai dari hal-hal sepele, seperti memilih menu makan atau tempat nongkrong, sebelum kamu terapkan pada keputusan yang lebih besar. Ingatkan juga dirimu bahwa keputusan yang "cukup baik" dan diambil tepat waktu, seringkali lebih berharga daripada keputusan "sempurna" yang datang terlambat.',
    "domains": {
        "karir": "Kebijaksanaanmu membuatmu cocok di peran yang butuh diplomasi dan pandangan netral, seperti manajemen tim lintas divisi, konsultasi, atau posisi yang menuntut kamu menjembatani kepentingan berbagai pihak. Rekan kerja mempercayaimu untuk mengambil keputusan yang adil bagi semua orang. Namun kebiasaan menimbang semua sisi terlalu lama bisa membuatmu terlihat lambat mengambil keputusan di mata atasan, terutama di situasi yang butuh respons cepat. Kamu juga cenderung menghindari posisi yang memaksamu memihak salah satu sisi secara tegas, meski kadang situasi memang menuntut ketegasan seperti itu. *PR: Ambil satu keputusan kerja minggu ini dalam waktu maksimal satu hari, tanpa menimbang berlarut-larut.*",
        "asmara": "Dalam hubungan, kebijaksanaanmu membuat pasangan merasa didengar dan dipahami dari berbagai sudut pandang, kamu jarang menghakimi buru-buru dan selalu berusaha adil dalam menilai situasi. Namun kehati-hatian ini bisa membuatmu sulit mengambil sikap tegas soal apa yang benar-benar kamu inginkan dari hubungan, kamu lebih sering menyesuaikan diri demi keharmonisan daripada menyuarakan kebutuhanmu sendiri. Pasangan mungkin merasa kesulitan menebak keinginanmu yang sesungguhnya, karena kamu terlalu sering mempertimbangkan perasaannya di atas perasaanmu sendiri. *PR: Sampaikan satu keinginanmu secara tegas ke pasangan minggu ini, tanpa embel-embel 'terserah kamu aja'.*",
        "keuangan": "Soal keuangan, sikap hati-hatimu membuatmu jarang terjebak keputusan finansial impulsif, kamu selalu mempertimbangkan berbagai opsi sebelum benar-benar memutuskan. Kestabilan ini membuat kondisi finansialmu cenderung aman dalam jangka panjang. Namun kebiasaan menimbang terlalu lama bisa membuatmu melewatkan peluang investasi yang sebenarnya sudah cukup jelas menguntungkan, karena kamu masih terus mempertimbangkan kemungkinan lain yang belum tentu lebih baik. *PR: Tetapkan tenggat waktu maksimal satu minggu untuk memutuskan satu peluang finansial yang sedang kamu pertimbangkan.*",
        "kesehatan": "Ketenangan dan sikap tidak terburu-buru membuatmu relatif jarang stres berlebihan menghadapi tekanan sehari-hari. Namun kebiasaan terus menimbang berbagai kemungkinan bisa membuat pikiranmu sulit benar-benar beristirahat, kamu terus memikirkan berbagai skenario bahkan untuk hal-hal yang sebenarnya sudah selesai atau tidak lagi relevan. Kamu perlu belajar melepaskan proses berpikir itu di waktu-waktu tertentu, supaya pikiranmu benar-benar dapat jeda. *PR: Coba tetapkan satu jam setiap malam khusus untuk berhenti memikirkan keputusan apa pun, dan benar-benar rileks.*",
    },
}
