"""Konten Weton — Wage."""

WAGE_CONTENT = {
    "tagline": "☾ Pasaran Wage",
    "chip": "WETON",
    "title": "{hari} Wage — Neptu {neptu}, Pribadi yang Mandiri",
    "p1_label": "Siapa Kamu",
    "p1": "Menurut primbon Jawa, kamu lahir dengan pasaran Wage, yang jatuh pada hari {hari} dengan neptu total {neptu}. Pasaran Wage sering dikaitkan dengan sosok yang mandiri dan punya pendirian kuat. Kamu tidak mudah terpengaruh pendapat orang lain, dan lebih memilih menentukan sendiri arah hidupmu berdasarkan penilaianmu sendiri. Sejak muda, kamu mungkin sudah terbiasa menyelesaikan masalahmu sendiri tanpa banyak melibatkan orang lain, bukan karena tidak peduli, tapi karena kamu memang merasa lebih nyaman mengandalkan kemampuan dan penilaianmu sendiri. Dalam lingkungan kerja, sikap ini membuatmu cocok memegang tanggung jawab yang butuh kemandirian tinggi, karena kamu jarang perlu diawasi ketat untuk tetap menyelesaikan tugas dengan baik. Orang-orang di sekitarmu menghormati keteguhan pendirianmu, meski kadang mereka juga merasa sulit benar-benar tahu apa yang sedang kamu pikirkan atau rasakan.",
    "p2_label": "Kekuatan & yang Perlu Dijaga",
    "p2": "Kemandirian dan keteguhan pendirianmu membuatmu jarang bergantung pada orang lain untuk merasa yakin. Kamu juga cenderung tenang menghadapi tekanan dari luar. Namun sikap mandiri ini kadang membuatmu enggan meminta bantuan bahkan ketika kamu benar-benar membutuhkannya, sehingga terasa lebih berat menjalani sesuatu sendirian. Sikap ini bisa membuat orang-orang terdekatmu merasa jauh darimu, bukan karena kamu tidak menyayangi mereka, tapi karena kamu terbiasa memendam kesulitan sendiri sampai benar-benar tuntas, atau sampai tidak tertahankan lagi. Ketika akhirnya kamu meminta bantuan, biasanya itu tandanya kamu memang sudah benar-benar kehabisan cara sendiri, padahal bantuan yang lebih dini bisa membuat prosesnya jauh lebih ringan.",
    "quote": "Kemandirian itu kekuatan, tapi meminta bantuan pada saat yang tepat juga bukan tanda kelemahan.",
    "p3_label": "PR Kecil Buat Kamu",
    "p3": "Coba minta bantuan pada satu hal kecil yang sebenarnya bisa kamu tangani sendiri, dan rasakan bahwa membiarkan orang lain membantu juga bisa terasa menenangkan. Kamu bisa mulai dari hal yang risikonya rendah, misalnya meminta tolong teman mengantarkan sesuatu atau mendiskusikan rencana kecil sebelum kamu jalankan sendiri. Perhatikan juga bagaimana perasaanmu setelah menerima bantuan itu; kemungkinan besar kamu akan sadar bahwa membuka diri sedikit tidak mengurangi kemandirianmu sama sekali.",
    "domains": {
        "karir": "Kemandirianmu adalah aset besar di dunia kerja, kamu bisa dipercaya memegang tanggung jawab tanpa perlu diawasi ketat, dan ini membuatmu cocok di peran individual contributor tingkat tinggi, freelance, atau posisi yang butuh inisiatif tanpa arahan detail. Atasan tahu kalau tugas diserahkan padamu, hasilnya akan tetap baik meski tanpa pengawasan ketat. Namun keengananmu meminta bantuan bisa membuatmu kesulitan sendiri saat beban kerja sebenarnya sudah berlebihan, dan kamu jarang mendelegasikan meski itu akan membuat pekerjaan lebih efisien. *PR: Delegasikan satu tugas ke rekan kerja minggu ini, meski kamu yakin bisa mengerjakannya sendiri lebih cepat.*",
        "asmara": "Dalam hubungan, kemandirianmu membuat pasangan merasa tidak perlu terus-menerus mengkhawatirkanmu, kamu bisa berdiri di atas kaki sendiri secara emosional maupun praktis. Namun kebiasaan memendam kesulitan sendiri bisa membuat pasangan merasa jauh darimu, mereka ingin dilibatkan dalam masalahmu tapi kamu jarang membuka pintu itu sampai benar-benar terpaksa. Keintiman yang sehat justru butuh keterbukaan yang lebih sering, bukan hanya saat keadaan sudah darurat. *PR: Ceritakan satu kesulitan kecil yang sedang kamu hadapi ke pasanganmu minggu ini, sebelum itu jadi terlalu berat untuk ditanggung sendiri.*",
        "keuangan": "Soal keuangan, kemandirianmu membuatmu terbiasa mengatur uangmu sendiri tanpa banyak bergantung pada bantuan orang lain, dan kamu cenderung punya rencana yang jelas untuk mencapai tujuan finansialmu sendiri. Namun sikap ini bisa membuatmu enggan mencari nasihat finansial dari orang lain, meski masukan dari sudut pandang berbeda kadang bisa membuka peluang yang belum kamu pertimbangkan. Kamu juga cenderung menanggung semua beban finansial keluarga sendirian tanpa membagi tanggung jawab, meski itu sebenarnya di luar kapasitasmu. *PR: Diskusikan satu rencana finansial dengan orang yang kamu percaya minggu ini, bukan cuma memutuskan sendirian.*",
        "kesehatan": "Kebiasaan menyelesaikan masalah sendirian membuatmu jarang meminta bantuan profesional, termasuk soal kesehatan, sampai kondisinya benar-benar tidak tertahankan. Kamu tipe yang akan terus mencoba mengatasi sendiri sebelum akhirnya menyerah dan mencari bantuan, padahal deteksi dan penanganan dini biasanya jauh lebih ringan. Beban yang kamu pendam sendirian, baik fisik maupun mental, juga bisa menumpuk tanpa disadari sampai berdampak pada energi dan staminamu sehari-hari. *PR: Kalau ada keluhan kesehatan yang sudah kamu tunda beberapa waktu, periksakan diri minggu ini, jangan ditangani sendiri lagi.*",
    },
}
