"""Konten Numerologi — 7."""

ANGKA_7_CONTENT = {
    "tagline": "✦ Angka Hidup 7",
    "chip": "NUMEROLOGI",
    "title": "Angka Hidup 7 — Pemikir Mendalam yang Penuh Perenungan",
    "p1_label": "Siapa Kamu",
    "p1": "Angka hidup 7 melambangkan kedalaman berpikir, rasa ingin tahu terhadap makna di balik sesuatu, dan kecenderungan untuk merenung. Kamu jarang puas dengan jawaban yang sederhana, dan selalu ingin memahami sesuatu sampai ke akarnya. Waktu sendiri terasa penting bagimu untuk mengolah pikiran dan menemukan kejernihan. Kamu biasanya lebih tertarik pada percakapan yang mendalam dibanding basa-basi ringan, dan senang mengeksplorasi topik-topik yang jarang dibahas orang kebanyakan. Dalam pekerjaan, kedalaman analisismu membuatmu unggul di bidang yang membutuhkan riset, pemikiran kritis, atau pemahaman mendalam terhadap suatu masalah. Kamu juga cenderung membutuhkan waktu sendirian secara teratur untuk mengisi ulang energi, karena terlalu banyak interaksi sosial bisa membuatmu merasa lelah secara mental.",
    "p2_label": "Kekuatan & yang Perlu Dijaga",
    "p2": "Kedalaman berpikirmu membuatmu bisa melihat sesuatu dari sudut pandang yang jarang terpikirkan orang lain. Kamu juga punya kemampuan analisis yang tajam. Namun kecenderungan untuk banyak merenung sendirian ini kadang membuatmu menjauh dari orang lain, sampai mereka merasa sulit benar-benar dekat denganmu. Kebiasaan memproses segalanya sendirian ini bisa membuat orang-orang terdekatmu merasa tidak diberi kesempatan untuk memahami apa yang sedang kamu pikirkan atau rasakan. Kamu juga bisa terjebak dalam analisis yang berlebihan, sampai sulit mengambil tindakan karena terus mencari pemahaman yang lebih sempurna.",
    "quote": "Perenungan yang dalam akan lebih bermakna kalau sesekali kamu bagikan hasilnya kepada orang lain.",
    "p3_label": "PR Kecil Buat Kamu",
    "p3": "Coba ajak satu orang terdekatmu berdiskusi tentang sesuatu yang sedang kamu pikirkan, alih-alih memprosesnya sendirian seperti biasa. Kamu juga bisa melatih diri menetapkan batas waktu untuk merenungkan sesuatu, misalnya satu atau dua hari, sebelum akhirnya memutuskan untuk bertindak, supaya perenungan tidak berubah menjadi penundaan yang berlarut-larut.",
    "domains": {
        "karir": "Kedalaman analisismu membuatmu unggul di bidang riset, strategi, atau apa pun yang butuh pemahaman mendalam sebelum bertindak, kamu jarang membuat keputusan dangkal. Namun kebiasaan memproses semuanya sendirian bisa membuat tim kesulitan memahami arah pikiranmu, dan kontribusimu yang sebenarnya berharga jadi kurang terlihat karena kamu jarang membagikannya secara terbuka. *PR: Bagikan satu insight atau analisismu secara terbuka di rapat tim minggu ini.*",
        "asmara": "Dalam hubungan, kedalaman perasaanmu membuat cinta yang kamu berikan terasa sungguh-sungguh, bukan sekadar permukaan. Namun kebutuhanmu akan waktu sendiri bisa membuat pasangan merasa dijauhi, terutama kalau kamu jarang menjelaskan bahwa itu caramu memulihkan energi, bukan tanda ada yang salah dengan hubungan. *PR: Jelaskan ke pasanganmu kenapa kamu butuh waktu sendiri, alih-alih membiarkannya menebak-nebak sendiri.*",
        "keuangan": "Soal keuangan, kecenderunganmu meriset mendalam sebelum memutuskan membuatmu jarang terjebak investasi yang tidak kamu pahami sepenuhnya. Namun analisis yang berlebihan bisa membuatmu kehilangan momentum, peluang bagus yang sebenarnya sudah cukup jelas bisa terlewat karena kamu masih terus mempertimbangkan. *PR: Tetapkan tenggat waktu satu minggu untuk memutuskan satu peluang finansial yang sedang kamu pertimbangkan.*",
        "kesehatan": "Kebutuhanmu akan waktu sendiri untuk merenung sebenarnya sehat untuk kesehatan mentalmu, tapi kalau berlebihan bisa membuatmu terisolasi dari dukungan sosial yang sebenarnya kamu butuhkan. Pikiranmu yang terus menganalisis juga bisa membuat sulit benar-benar rileks. *PR: Ajak satu orang terdekat berdiskusi tentang sesuatu yang sedang kamu pikirkan minggu ini, alih-alih memprosesnya sendirian.*",
    },
}
