"""Konten Numerologi — 1."""

ANGKA_1_CONTENT = {
    "tagline": "✦ Angka Hidup 1",
    "chip": "NUMEROLOGI",
    "title": "Angka Hidup 1 — Sang Pemula yang Mandiri",
    "p1_label": "Siapa Kamu",
    "p1": "Angka hidup 1 dihitung dari penjumlahan digit tanggal lahirmu, dan dalam numerologi angka ini melambangkan jiwa kepemimpinan serta kemandirian yang kuat. Kamu cenderung suka memulai sesuatu dari nol dan tidak terlalu nyaman hanya mengikuti arahan orang lain. Ada dorongan alami dalam dirimu untuk menjadi yang terdepan. Dorongan ini biasanya sudah terlihat sejak kecil, misalnya lewat kebiasaan ingin menyelesaikan sesuatu dengan caramu sendiri, bukan cara yang diajarkan orang lain begitu saja. Dalam pekerjaan, kamu cocok mengisi peran yang membutuhkan inisiatif tinggi, seperti merintis proyek baru atau memimpin tim yang sedang membangun sesuatu dari awal. Kamu jarang puas hanya jadi bagian kecil dari sistem yang sudah ada; kamu ingin punya andil nyata dalam menentukan arah sesuatu berjalan.",
    "p2_label": "Kekuatan & yang Perlu Dijaga",
    "p2": "Inisiatif dan kepercayaan dirimu membuat orang lain sering melihatmu sebagai penggerak utama dalam sebuah kelompok. Kamu juga berani mengambil keputusan tanpa harus menunggu persetujuan banyak pihak. Namun dorongan untuk selalu memimpin ini kadang membuatmu kurang sabar bekerja sama, atau sulit menerima ide dari orang lain. Kebutuhan untuk selalu berada di posisi terdepan ini bisa membuat rekan kerja atau anggota timmu merasa kurang dilibatkan dalam pengambilan keputusan, meski niatmu sebenarnya baik. Kamu juga bisa terlalu cepat mengambil alih sebuah proses, tanpa memberi kesempatan orang lain untuk berkembang dan belajar dari kesalahan mereka sendiri.",
    "quote": "Menjadi pemimpin yang baik juga berarti tahu kapan harus mengikuti arahan orang lain.",
    "p3_label": "PR Kecil Buat Kamu",
    "p3": "Coba biarkan satu keputusan kecil diambil oleh orang lain di sekitarmu, dan lihat bagaimana rasanya melepaskan kendali sejenak. Latih juga dirimu untuk bertanya pendapat rekan kerja atau teman sebelum langsung menetapkan arah, meski kamu sudah punya gambaran jelas di kepala. Kebiasaan kecil ini akan membuat orang lain merasa lebih dihargai dan dilibatkan dalam proses yang kamu pimpin.",
    "domains": {
        "karir": "Jiwa kepemimpinanmu membuatmu cocok merintis sesuatu dari nol, entah itu membangun tim baru, memulai usaha sendiri, atau memimpin proyek yang belum punya cetak biru jelas. Kamu tidak takut jadi orang pertama yang mengambil langkah, dan itu membuatmu dipercaya memegang posisi yang butuh inisiatif tinggi. Namun dorongan untuk selalu memimpin bisa membuatmu sulit menerima posisi sebagai anggota tim biasa, kamu merasa gelisah kalau tidak punya kendali penuh atas arah sebuah proyek. Kamu juga berisiko dianggap terlalu dominan oleh atasan atau rekan kerja yang sama-sama punya ambisi memimpin. *PR: Ambil satu peran sebagai anggota tim biasa minggu ini, dan biarkan orang lain memimpin arahnya.*",
        "asmara": "Dalam hubungan, kepercayaan dirimu membuat pasangan merasa aman karena kamu jelas tahu apa yang kamu mau dan berani mengambil langkah pertama. Namun dorongan untuk selalu memegang kendali bisa membuat pasangan merasa keputusan-keputusan penting dalam hubungan selalu diarahkan olehmu, jarang benar-benar jadi keputusan berdua. Kamu perlu belajar bahwa hubungan yang sehat adalah kepemimpinan bergilir, bukan satu pihak yang selalu di depan. *PR: Biarkan pasanganmu yang memutuskan satu rencana kencan berikutnya, tanpa kamu ikut campur mengarahkan.*",
        "keuangan": "Soal keuangan, semangat merintismu membuatmu berani memulai usaha sendiri atau sumber penghasilan baru yang belum pernah kamu coba. Kamu percaya diri dengan kemampuanmu menghasilkan uang dari nol. Namun dorongan untuk selalu mengendalikan sendiri urusan finansial bisa membuatmu enggan berbagi keputusan keuangan dengan pasangan atau partner bisnis, bahkan saat keputusan bersama sebenarnya lebih tepat. *PR: Diskusikan satu keputusan finansial dengan orang lain minggu ini sebelum memutuskan sendiri.*",
        "kesehatan": "Energi dan dorongan untuk selalu bergerak maju membuatmu jarang diam, tapi ini juga bisa membuatmu memaksakan diri terus produktif tanpa memberi tubuh waktu istirahat yang layak. Kamu tipe yang sulit menerima keterbatasan fisik, merasa harus tetap kuat memimpin meski sedang tidak fit. *PR: Kalau tubuhmu memberi sinyal lelah minggu ini, izinkan diri berhenti tanpa merasa gagal.*",
    },
}
