"""Konten Numerologi — 6."""

ANGKA_6_CONTENT = {
    "tagline": "✦ Angka Hidup 6",
    "chip": "NUMEROLOGI",
    "title": "Angka Hidup 6 — Pengasuh yang Penuh Tanggung Jawab",
    "p1_label": "Siapa Kamu",
    "p1": "Angka hidup 6 melambangkan kepedulian, tanggung jawab, dan cinta terhadap keluarga maupun orang-orang terdekat. Kamu cenderung merasa bertanggung jawab menjaga kesejahteraan orang di sekitarmu, bahkan kadang lebih dari kesejahteraanmu sendiri. Kehadiranmu membuat orang lain merasa diperhatikan dan diurus dengan baik. Sejak muda, kamu mungkin sudah terbiasa mengambil peran mengurus orang lain, entah itu adik, teman, atau anggota keluarga yang membutuhkan bantuan. Dalam pekerjaan, sisi pengasuhmu membuatmu cocok di peran yang berhubungan langsung dengan kesejahteraan orang lain, seperti mengelola tim, pendidikan, atau bidang layanan yang membutuhkan empati tinggi. Dalam keluarga, kamu sering jadi sosok yang menjaga semuanya tetap berjalan baik, bahkan ketika tidak ada yang secara eksplisit memintamu melakukannya.",
    "p2_label": "Kekuatan & yang Perlu Dijaga",
    "p2": "Kepedulian dan tanggung jawabmu membuat orang-orang terdekat merasa aman dan diperhatikan. Kamu juga rela berkorban demi kebahagiaan orang yang kamu sayangi. Namun kebiasaan mengutamakan orang lain ini kadang membuatmu lupa mengurus kebutuhanmu sendiri, sampai akhirnya kamu yang kelelahan tanpa disadari orang di sekitarmu. Pola mengurus orang lain tanpa henti ini, kalau dibiarkan terus, bisa membuatmu merasa hampa atau lelah secara emosional, terutama saat kebaikanmu tidak dihargai atau bahkan dianggap wajar oleh orang-orang yang terbiasa menerima perhatianmu.",
    "quote": "Merawat orang lain akan lebih berkelanjutan kalau kamu juga merawat dirimu sendiri.",
    "p3_label": "PR Kecil Buat Kamu",
    "p3": "Luangkan satu waktu khusus yang benar-benar untuk mengurus kebutuhanmu sendiri, tanpa merasa bersalah karena tidak sedang mengurus orang lain. Kamu bisa membuat jadwal sederhana untuk waktu pribadi ini, dan perlakukan itu sepenting janji dengan orang lain, supaya kamu tidak mudah membatalkannya demi mengurus kebutuhan orang lain lebih dulu.",
    "domains": {
        "karir": "Sisi pengasuhmu membuatmu cocok di peran yang berhubungan langsung dengan kesejahteraan orang lain, seperti manajemen tim, HR, pendidikan, atau layanan yang butuh empati tinggi. Rekan kerja merasa diperhatikan olehmu, bukan hanya dinilai dari performa. Namun kebiasaan mengurus urusan orang lain bisa membuatmu kelebihan beban kerja, kamu sulit menolak permintaan tolong meski di luar tanggung jawabmu, dan itu bisa membuat kontribusimu sendiri kurang diakui karena energimu habis membantu tugas orang lain. *PR: Tolak satu permintaan tolong yang di luar tanggung jawabmu di kantor minggu ini.*",
        "asmara": "Dalam hubungan, kepedulianmu membuat pasangan merasa benar-benar diurus dan diperhatikan, kamu selalu memikirkan kenyamanannya lebih dulu. Namun kebiasaan mengutamakan orang lain ini bisa membuat kebutuhan emosionalmu sendiri jarang tersampaikan, sampai pasangan tidak benar-benar tahu apa yang membuatmu bahagia atau lelah. Kamu perlu belajar bahwa menerima perhatian sama pentingnya dengan memberi perhatian. *PR: Minta satu hal yang kamu butuhkan dari pasanganmu minggu ini, bukan menunggu dia menebaknya sendiri.*",
        "keuangan": "Soal keuangan, rasa tanggung jawabmu terhadap keluarga membuatmu rela mengorbankan kebutuhanmu sendiri demi kesejahteraan orang terdekat. Ini mulia, tapi kalau berlebihan bisa membuat rencana finansial pribadimu sendiri tertunda terus-menerus, kamu selalu jadi pihak yang membantu, jarang jadi pihak yang dibantu. *PR: Sisihkan satu pos tabungan khusus untuk dirimu sendiri sebelum membantu kebutuhan orang lain bulan ini.*",
        "kesehatan": "Kebiasaan mengurus orang lain sebelum diri sendiri bisa membuatmu mengabaikan kelelahanmu sendiri sampai benar-benar terasa berat. Kamu tipe yang baru istirahat kalau semua urusan orang lain sudah beres, padahal itu jarang benar-benar terjadi. Kelelahan yang ditumpuk ini bisa berdampak pada stamina dan daya tahan tubuhmu dalam jangka panjang. *PR: Jadwalkan satu waktu istirahat wajib minggu ini yang tidak bisa digeser oleh urusan orang lain.*",
    },
}
