"""Konten Numerologi — 5."""

ANGKA_5_CONTENT = {
    "tagline": "✦ Angka Hidup 5",
    "chip": "NUMEROLOGI",
    "title": "Angka Hidup 5 — Petualang yang Haus Kebebasan",
    "p1_label": "Siapa Kamu",
    "p1": "Angka hidup 5 melambangkan kebebasan, perubahan, dan rasa ingin tahu yang besar terhadap pengalaman baru. Kamu tidak suka terjebak dalam rutinitas yang monoton, dan selalu tertarik mencoba hal-hal yang belum pernah kamu lakukan sebelumnya. Hidup terasa lebih bermakna bagimu ketika penuh variasi. Kamu biasanya punya keingintahuan yang tinggi terhadap banyak hal, mulai dari tempat-tempat baru, budaya yang berbeda, sampai ide-ide yang menantang cara pandang lamamu. Dalam pekerjaan, kamu cocok di lingkungan yang dinamis dan memberi ruang untuk mencoba pendekatan baru, karena kamu cepat merasa jenuh dengan rutinitas yang itu-itu saja. Dalam pergaulan, kamu adalah sosok yang selalu punya cerita menarik untuk dibagikan, karena kamu jarang menolak kesempatan untuk mencoba sesuatu yang baru.",
    "p2_label": "Kekuatan & yang Perlu Dijaga",
    "p2": "Keluwesan dan keberanianmu mencoba hal baru membuat hidupmu jarang terasa membosankan. Kamu juga mudah beradaptasi dengan lingkungan yang berbeda-beda. Namun kecintaan pada kebebasan ini kadang membuatmu kesulitan berkomitmen pada satu hal dalam jangka panjang, karena selalu ada godaan untuk berpindah ke hal yang baru. Pola ini bisa membuat orang-orang terdekatmu merasa tidak yakin seberapa lama kamu akan bertahan pada satu keputusan, entah itu pekerjaan, hubungan, maupun rencana jangka panjang. Kamu juga bisa terjebak dalam siklus mencari kebahagiaan lewat pengalaman baru, tanpa pernah benar-benar mendalami satu hal sampai merasakan kepuasan yang lebih utuh.",
    "quote": "Kebebasan akan terasa lebih bermakna kalau sesekali kamu memberi ruang bagi komitmen untuk tumbuh.",
    "p3_label": "PR Kecil Buat Kamu",
    "p3": "Pilih satu komitmen yang sudah kamu buat, lalu pertahankan konsistensinya tanpa tergoda mencari variasi baru. Kamu bisa membuat kesepakatan dengan dirimu sendiri untuk bertahan pada satu hal selama jangka waktu tertentu, misalnya tiga bulan, sebelum menilai apakah kamu benar-benar ingin berpindah atau ternyata konsistensi itu membawa hasil yang lebih memuaskan dari yang kamu kira.",
    "domains": {
        "karir": "Keluwesanmu membuatmu cocok di pekerjaan yang dinamis dan penuh variasi, seperti sales lapangan, event, atau peran yang mengharuskanmu bertemu banyak orang baru. Namun kecenderungan mudah bosan bisa membuatmu berpindah pekerjaan sebelum benar-benar menuai hasil. *PR: Komit menyelesaikan satu proyek yang sedang berjalan sebelum memulai yang baru.*",
        "asmara": "Dalam asmara, energi dan rasa ingin tahumu membuat hubungan terasa seru dan jarang membosankan, kamu suka mengajak pasangan mencoba hal baru bersama, entah tempat baru, hobi baru, atau sekadar rencana dadakan yang membuat hubungan terasa hidup. Namun rasa takut terjebak dalam rutinitas bisa membuatmu ragu berkomitmen serius, karena komitmen terasa seperti kehilangan kebebasan. Pasangan mungkin merasa tidak yakin seberapa jauh mereka bisa mengandalkan keseriusanmu, terutama kalau kamu sering menghindari pembicaraan soal masa depan hubungan kalian. *PR: Ajak pasanganmu bicara terbuka soal satu rencana jangka panjang minggu ini, tanpa menghindar seperti biasanya.*",
        "keuangan": "Soal uang, sifat spontanmu membuatmu tidak ragu membelanjakan untuk pengalaman baru, entah jalan-jalan, kelas baru, atau mencoba sesuatu yang belum pernah kamu lakukan, karena kamu percaya hidup harus dinikmati bukan cuma ditabung untuk masa depan yang belum pasti. Namun kebiasaan ini bisa membuat tabunganmu jarang benar-benar bertambah, karena begitu ada uang lebih, dorongan untuk segera menggunakannya untuk hal baru selalu muncul lebih dulu dibanding niat menabung. *PR: Buat rekening tabungan terpisah yang auto-debet setiap gajian, supaya kamu tidak sempat tergoda memakainya.*",
        "kesehatan": "Energimu yang tinggi membuatmu jarang diam, dan itu bagus untuk kebugaran fisik, tapi gaya hidupmu yang serba cepat dan berpindah-pindah bisa membuat pola makan dan tidurmu jadi tidak teratur, kamu mungkin sering melewatkan waktu makan atau begadang karena terlalu asyik dengan aktivitas baru. Ketidaktetapan jadwal ini, kalau dibiarkan terus, bisa berdampak ke stamina jangka panjangmu. *PR: Tetapkan satu jam tidur yang konsisten selama seminggu ke depan, meski hari-harimu terasa berbeda-beda.*",
    },
}
