"""Konten Zodiak — Aquarius."""

AQUARIUS_CONTENT = {
    "tagline": "☉ Matahari di Aquarius",
    "chip": "ZODIAK",
    "title": "Aquarius — Pemikir yang Out of the Box",
    "p1_label": "Siapa Kamu",
    "p1": "Kamu lahir saat matahari berada di rasi Aquarius, rasi yang identik dengan pemikiran yang unik dan cara pandang yang sering berbeda dari kebanyakan orang. Kamu tidak terlalu peduli mengikuti arus, dan lebih tertarik memikirkan bagaimana sesuatu bisa diperbaiki atau dilakukan dengan cara yang belum pernah dicoba orang lain. Kamu juga punya kepedulian besar terhadap isu-isu yang lebih luas dari dirimu sendiri. Cara berpikirmu yang unik ini sering membuatmu jadi orang yang pertama kali mengusulkan ide-ide yang di awal terdengar aneh, tapi belakangan ternyata masuk akal dan bahkan diikuti banyak orang. Dalam pekerjaan, kamu cocok mengisi peran yang membutuhkan inovasi dan pemikiran di luar kebiasaan. Dalam pergaulan, kamu punya lingkaran pertemanan yang beragam, karena kamu jarang menilai orang dari latar belakang atau kelompok sosialnya.",
    "p2_label": "Kekuatan & yang Perlu Dijaga",
    "p2": "Orisinalitas dan idealismemu membuat orang lain terinspirasi untuk berpikir lebih terbuka. Kamu juga cenderung objektif dan tidak mudah terbawa emosi dalam menilai sesuatu. Namun kebiasaan menjaga jarak secara emosional ini kadang membuat orang-orang terdekatmu merasa sulit benar-benar memahami apa yang sedang kamu rasakan. Kecenderungan untuk lebih nyaman membicarakan ide dan konsep dibanding perasaan pribadi ini bisa membuat hubungan dekatmu terasa kurang intim, meski sebenarnya kamu peduli dengan cara yang berbeda. Kamu juga bisa terlalu terpaku pada idealisme, sampai sulit menerima bahwa dunia nyata tidak selalu bisa berjalan seideal yang kamu bayangkan.",
    "quote": "Ide-ide besar akan lebih bermakna kalau kamu juga membiarkan orang lain melihat sisi personalmu.",
    "p3_label": "PR Kecil Buat Kamu",
    "p3": "Coba ceritakan satu perasaan pribadi, bukan hanya pendapat atau ide, kepada orang terdekatmu, dan biarkan mereka melihat sisi dirimu yang biasanya kamu jaga rapat-rapat. Latihan ini bisa dimulai dari hal kecil, seperti mengakui saat kamu merasa sedih atau khawatir, alih-alih langsung mengalihkan pembicaraan ke topik yang lebih abstrak dan aman secara emosional.",
    "domains": {
        "karir": "Kamu unggul di pekerjaan yang butuh inovasi dan cara pandang baru, sering jadi orang yang mengusulkan pendekatan berbeda saat orang lain masih terpaku pada cara lama. Tapi kurang cocok di lingkungan yang sangat kaku aturan dan hierarkis, karena kamu merasa terkekang harus mengikuti prosedur yang menurutmu sudah tidak relevan lagi. *PR: kalau terjebak sistem kaku, cari satu celah kecil buat menyalurkan ide inovatifmu tanpa melanggar aturan besar.*",
        "asmara": "Kamu butuh pasangan yang menghargai kebebasan berpikirmu dan tidak menuntutmu jadi orang yang konvensional. Tapi kamu sendiri susah menunjukkan sisi emosional atau vulnerable, bikin hubungan terasa kurang intim, karena kamu lebih nyaman membicarakan ide dan konsep dibanding perasaan yang lebih dalam. *PR: coba ungkapkan satu perasaan, bukan ide atau pendapat, ke pasangan secara langsung.*",
        "keuangan": "Kamu cenderung belanja untuk gadget, hal-hal unik, atau donasi ke isu sosial yang kamu pedulikan, karena bagimu mendukung sesuatu yang bermakna lebih penting dari sekadar menabung. Tapi kurang perhatian ke tabungan konvensional, sampai kondisi finansial jangka panjangmu jadi kurang terencana. *PR: buat 1 rekening terpisah khusus tabungan yang tidak kamu sentuh sama sekali.*",
        "kesehatan": "Pikiranmu sering terlalu aktif menjelang tidur, banyak ide berputar yang bikin susah benar-benar rileks, karena otakmu terus memproses konsep dan kemungkinan baru bahkan saat tubuh sudah lelah. Sistem sirkulasi dan pergelangan kaki cenderung jadi titik lemah kalau ketegangan mental ini dibiarkan menumpuk. *PR: jadwalkan digital detox rutin sebelum tidur, minimal 30 menit tanpa layar.*",
    },
}
