"""Konten Zodiak — Aries."""

ARIES_CONTENT = {
    "tagline": "☉ Matahari di Aries",
    "chip": "ZODIAK",
    "title": "Aries — Sang Pemberani yang Cepat Bergerak",
    "p1_label": "Siapa Kamu",
    "p1": "Kamu lahir saat matahari berada di rasi Aries, rasi pertama dalam siklus zodiak, dan itu tercermin dari caramu menghadapi hidup: berani mengambil langkah pertama saat orang lain masih ragu. Energi dalam dirimu terasa cepat menyala, membuatmu jarang betah berlama-lama di zona nyaman. Begitu ada tantangan baru, biasanya kamu yang paling dulu maju, bukan karena tidak takut, tapi karena kamu memilih untuk tidak membiarkan rasa takut itu menahanmu. Sifat ini sudah terlihat sejak kamu masih muda, misalnya lewat kebiasaan mengangkat tangan lebih dulu untuk mencoba sesuatu yang baru, atau memilih jalan yang belum pernah dilalui orang lain di sekitarmu. Dalam pekerjaan, energi ini membuatmu cocok mengisi peran perintis, seperti membuka proyek baru atau memimpin tim yang sedang membangun sesuatu dari nol. Dalam pertemanan, kamu sering jadi orang yang mengajak teman-temanmu keluar dari rutinitas dan mencoba pengalaman baru bersama.",
    "p2_label": "Kekuatan & yang Perlu Dijaga",
    "p2": 'Keberanian dan inisiatifmu membuat orang lain sering menjadikanmu contoh soal cara memulai sesuatu. Kamu juga jujur soal apa yang kamu rasakan, sehingga orang tahu persis di mana posisi mereka di matamu. Namun semangat yang menyala cepat itu kadang juga padam secepat itu pula, membuat beberapa rencana besar berhenti di tengah jalan sebelum sempat kamu selesaikan. Pola "semangat di awal, hilang di tengah jalan" ini bisa membuat orang lain ragu mempercayakan proyek jangka panjang kepadamu, meski mereka tahu betul kamu adalah orang paling tepat untuk memulai sesuatu. Kejujuranmu yang spontan juga kadang keluar tanpa penyaringan, sehingga bisa menyakiti perasaan orang lain meski itu bukan niatmu.',
    "quote": "Keberanian akan terasa jauh lebih berarti kalau disertai dengan kesabaran untuk menyelesaikannya.",
    "p3_label": "PR Kecil Buat Kamu",
    "p3": "Coba pilih satu hal kecil yang sempat kamu tinggalkan setengah jalan, lalu selesaikan sampai tuntas sebelum memulai hal baru yang lain. Rasakan bedanya ketika kamu benar-benar menuntaskan sesuatu, bukan cuma memulainya. Kamu bisa membuat kesepakatan sederhana dengan dirimu sendiri: setiap kali ide baru muncul saat sedang mengerjakan sesuatu, tuliskan dulu ide itu di catatan terpisah, dan kembali fokus menyelesaikan yang sedang berjalan. Dengan begitu, semangat awalmu tetap tersalurkan tanpa mengorbankan penyelesaian yang sudah dimulai.",
    "domains": {
        "karir": "Kamu bersinar di proyek rintisan atau posisi yang butuh orang berani ambil langkah pertama, misalnya buka lini bisnis baru, jadi orang pertama yang menawarkan ide di rapat, atau memimpin tim yang baru dibentuk dari nol. Tapi begitu proyeknya masuk fase rutin dan repetitif, semangatmu gampang kendur, dan kamu bisa kehilangan minat tepat di fase yang justru paling menentukan hasil akhirnya. Rekan kerja kadang was-was menyerahkan tugas jangka panjang kepadamu karena sudah melihat pola ini berulang kali, meski mereka tahu betul kamu adalah orang paling tepat untuk memulai sesuatu dari nol. *PR: minta satu rekan pegang bagian follow-up/detail administratif dari proyekmu, biar energimu tetap tersalur ke bagian yang benar-benar kamu kuasai.*",
        "asmara": 'Kamu jujur dan langsung soal perasaan, bikin pasangan tahu persis posisinya tanpa perlu menebak-nebak, dan itu jadi kekuatan besar buat hubungan yang jujur. Tapi kesabaranmu diuji kalau hubungan terasa monoton, kamu butuh hal baru supaya percikan itu tetap ada, dan kalau tidak ada, kamu bisa jadi gelisah atau mulai mencari-cari kesalahan kecil dalam hubungan yang sebenarnya baik-baik saja. Pasanganmu mungkin merasa harus terus menciptakan kejutan supaya kamu tetap tertarik, padahal hubungan yang matang juga butuh momen-momen tenang. *PR: sebelum menganggap hubungan membosankan, coba dulu ajak pasangan bikin "hal baru" bareng, bukan langsung mundur atau mencari yang lain.*',
        "keuangan": 'Kamu gampang tergoda beli sesuatu yang baru dan menarik perhatian saat itu juga, tanpa banyak mikir jangka panjang, karena dorongan untuk segera memiliki sesuatu yang kamu inginkan terasa begitu kuat. Ini bikin belanja impulsif jadi kebiasaan yang sering bikin kaget pas cek saldo di akhir bulan, apalagi kalau kamu sedang dalam mood yang sedang tinggi dan merasa layak "reward diri sendiri". Kamu juga cenderung tidak sabar menunggu diskon atau promo, lebih memilih beli sekarang meski harganya belum tentu paling murah. *PR: kasih jeda 24 jam sebelum beli barang di atas nominal tertentu, supaya dorongan awal itu sempat mereda dulu.*',
        "kesehatan": 'Energimu besar dan butuh disalurkan lewat gerak fisik yang intens, kalau nggak malah jadi gelisah, susah diam, atau gampang emosi tanpa sebab yang jelas. Risikonya, kamu sering terburu-buru tanpa pemanasan cukup saat olahraga atau aktivitas fisik lainnya, jadi rawan cedera otot atau sendi, terutama di bagian kepala dan wajah yang jadi titik lemah khas Aries. Kamu juga tipe yang memaksakan diri tetap aktif meski tubuh sudah memberi sinyal lelah, karena tidak suka merasa "kalah" oleh keterbatasan fisik sendiri. *PR: biasakan pemanasan 5 menit sebelum olahraga, sekecil apa pun rasanya buang-buang waktu.*',
    },
}
