"""Konten Zodiak — Cancer."""

CANCER_CONTENT = {
    "tagline": "☉ Matahari di Cancer",
    "chip": "ZODIAK",
    "title": "Cancer — Pelindung yang Penuh Perasaan",
    "p1_label": "Siapa Kamu",
    "p1": "Matahari berada di rasi Cancer saat kamu lahir, dan itu membuatmu punya kepekaan emosi yang dalam terhadap dirimu sendiri maupun orang-orang di sekitarmu. Rumah dan keluarga, baik dalam arti sebenarnya maupun orang-orang yang kamu anggap keluarga, punya tempat yang sangat penting dalam hidupmu. Kamu cenderung melindungi orang-orang terdekat dengan sepenuh hati, bahkan sebelum diminta. Kepekaanmu ini membuatmu mudah mengingat momen-momen emosional, baik yang menyenangkan maupun yang menyakitkan, dan momen-momen itu sering membentuk cara kamu memperlakukan orang lain di masa depan. Dalam hubungan, kamu adalah tipe orang yang benar-benar hadir saat orang lain sedang kesulitan, siap mendengarkan tanpa perlu diminta. Di lingkungan kerja, sisi pengasuh ini juga muncul lewat caramu memperhatikan kesejahteraan rekan-rekan setim, bukan hanya fokus pada hasil kerja semata.",
    "p2_label": "Kekuatan & yang Perlu Dijaga",
    "p2": "Empati dan kepedulianmu membuat orang lain merasa aman menceritakan hal-hal yang berat kepadamu. Kamu juga punya ingatan emosional yang kuat, sehingga bisa mengenali perasaan seseorang bahkan dari hal-hal kecil. Sisi sensitif ini terkadang membuatmu mudah terbawa suasana hati, atau menyimpan kekecewaan lebih lama dari yang seharusnya. Kamu bisa jadi terlalu protektif terhadap orang-orang yang kamu sayangi, sampai tanpa sadar membatasi ruang gerak mereka karena rasa khawatirmu yang berlebihan. Ingatan emosionalmu yang kuat juga bisa jadi pedang bermata dua, karena kamu cenderung terus mengingat luka lama meski orang lain sudah lama melupakannya.",
    "quote": "Melindungi orang lain itu indah, tapi jangan sampai lupa melindungi perasaanmu sendiri juga.",
    "p3_label": "PR Kecil Buat Kamu",
    "p3": "Ketika ada perasaan yang mengganjal, coba tuliskan atau ceritakan langsung kepada orang yang bersangkutan, alih-alih memendamnya sendirian sampai berlarut-larut. Kamu juga bisa melatih diri untuk melepaskan satu kekecewaan lama yang sebenarnya sudah tidak relevan lagi, dengan cara menuliskannya dan secara sadar memutuskan untuk tidak membawanya lagi ke hubungan yang sedang berjalan sekarang.",
    "domains": {
        "karir": 'Kamu unggul di peran yang butuh empati, memperhatikan kesejahteraan tim, menjaga suasana kerja tetap hangat, dan rekan-rekan biasanya merasa nyaman bercerita masalah pribadi maupun pekerjaan denganmu. Risikonya, kritik terhadap pekerjaanmu bisa terasa seperti serangan pribadi, dan kamu bisa terbawa perasaan berhari-hari hanya karena satu masukan kecil dari atasan. Kamu juga cenderung menyimpan kekecewaan soal keputusan kerja yang menurutmu tidak adil, meski tidak selalu menunjukkannya secara terbuka. *PR: latih diri memisahkan "kerjaanku dikritik" dari "aku sebagai orang dikritik".*',
        "asmara": "Kamu pasangan yang penuh perhatian dan protektif, selalu memastikan orang yang kamu sayangi merasa aman dan diperhatikan dalam segala hal. Tapi kadang sikap protektifmu berubah jadi posesif tanpa disadari, atau kamu diam-diam ngambek tanpa bilang apa masalahnya, berharap pasangan bisa menebak sendiri apa yang salah. Pola ini bisa membuat pasangan merasa bingung dan sering salah menafsirkan suasana hatimu yang naik turun. *PR: kalau ada yang mengganjal, bilang langsung, jangan biarkan pasangan menebak-nebak lewat sikap dingin.*",
        "keuangan": "Kamu rajin menabung untuk keluarga atau rumah, dan biasanya punya rencana yang cukup matang soal masa depan finansial orang-orang yang kamu sayangi. Tapi gampang belanja impulsif saat mood sedang turun sebagai bentuk menghibur diri sendiri, entah lewat makanan, barang kesukaan, atau hal-hal kecil yang memberi rasa nyaman sesaat. Kebiasaan ini kalau tidak disadari bisa menumpuk jadi pengeluaran yang cukup besar dalam sebulan. *PR: kalau lagi sedih dan pengen belanja, tunda dulu satu hari, cek lagi apa benar butuh.*",
        "kesehatan": "Perasaanmu yang naik-turun sering berdampak ke perutmu, gampang mual atau perih pas lagi stres atau cemas, karena secara fisik kamu memang cukup sensitif terhadap tekanan emosional. Kamu juga cenderung memendam kekhawatiran sampai berdampak ke pola tidur, sering terbangun malam hari karena pikiran yang terus berputar soal orang-orang yang kamu khawatirkan. *PR: jaga jam makan tetap teratur meski lagi banyak pikiran, jangan sampai telat atau lupa makan sama sekali.*",
    },
}
