"""Konten Zodiak — Gemini."""

GEMINI_CONTENT = {
    "tagline": "☉ Matahari di Gemini",
    "chip": "ZODIAK",
    "title": "Gemini — Si Lincah yang Serba Ingin Tahu",
    "p1_label": "Siapa Kamu",
    "p1": "Kamu lahir saat matahari berada di rasi Gemini, rasi yang identik dengan rasa ingin tahu yang besar dan kemampuan berkomunikasi yang luwes. Pikiranmu bergerak cepat dari satu topik ke topik lain, dan kamu jarang merasa bosan selama masih ada hal baru untuk dipelajari atau dibicarakan. Kemampuanmu menyesuaikan diri di berbagai lingkaran pertemanan membuatmu terasa mudah akrab dengan banyak orang. Kamu biasanya punya banyak minat sekaligus, dari topik ringan sampai yang cukup serius, dan senang menjadi penghubung informasi antara satu kelompok dengan kelompok lainnya. Dalam pekerjaan, kelincahan berpikirmu membuatmu cocok di peran yang butuh komunikasi lintas tim atau menangani banyak jenis tugas sekaligus. Di lingkungan sosial, kamu adalah tipe orang yang selalu punya bahan obrolan baru, membuat percakapan denganmu jarang terasa membosankan.",
    "p2_label": "Kekuatan & yang Perlu Dijaga",
    "p2": "Keluwesanmu dalam berbicara dan beradaptasi membuat orang lain merasa nyaman bertukar cerita denganmu. Kamu juga cepat menangkap ide baru dan menghubungkannya dengan hal-hal yang sudah kamu ketahui sebelumnya. Namun rasa ingin tahu yang terlalu banyak arah kadang membuatmu kesulitan fokus menyelesaikan satu hal sampai benar-benar tuntas. Kecenderungan berpindah topik atau minat ini bisa membuat orang lain merasa kamu kurang konsisten, meski sebenarnya itu murni karena rasa ingin tahumu yang tidak pernah habis. Kamu juga bisa terjebak mengetahui banyak hal secara permukaan, tanpa benar-benar mendalami satu bidang sampai jadi ahli di dalamnya.",
    "quote": "Rasa ingin tahu akan membawamu jauh, asal kamu juga tahu kapan harus berhenti menjelajah dan mulai mendalami.",
    "p3_label": "PR Kecil Buat Kamu",
    "p3": "Pilih satu proyek atau kebiasaan yang sudah lama ingin kamu kuasai, lalu fokuskan waktumu di situ secara konsisten tanpa berpindah ke hal lain. Lihat seberapa jauh kamu bisa berkembang kalau perhatianmu tidak terpecah. Kamu bisa mencoba menetapkan waktu khusus setiap minggu yang benar-benar didedikasikan untuk satu topik itu saja, dan menahan diri untuk tidak beralih ke minat baru selama waktu tersebut berlangsung.",
    "domains": {
        "karir": "Kamu jago di peran yang butuh komunikasi lintas tim atau menangani banyak hal sekaligus, dan atasan biasanya senang punya kamu di tim karena selalu bisa diandalkan menjembatani informasi antar divisi. Tapi bisa keteteran menyelesaikan satu proyek besar sampai tuntas karena gampang tergoda tugas baru yang lebih menarik, dan kamu bisa punya banyak pekerjaan setengah jalan di saat yang sama. Rekan kerja mungkin melihatmu sebagai sosok multitasking, tapi juga sedikit ragu soal seberapa dalam kamu benar-benar menguasai satu bidang tertentu. *PR: sebelum terima tanggung jawab baru, selesaikan dulu satu yang sedang jalan sampai kelar.*",
        "asmara": "Kamu butuh obrolan yang hidup dan bervariasi supaya hubungan terasa segar, dan gampang bosan kalau komunikasi jadi datar atau itu-itu saja setiap harinya. Risikonya, kamu bisa terlihat kurang serius di mata pasangan yang butuh kepastian, karena kamu sering mengalihkan topik berat dengan candaan atau obrolan ringan. Pasangan mungkin merasa sulit benar-benar tahu isi hatimu, karena kamu lebih nyaman berbicara tentang ide dibanding perasaan yang lebih dalam. *PR: sesekali dengarkan cerita pasangan sampai habis tanpa buru-buru ganti topik.*",
        "keuangan": "Kamu suka coba banyak hal baru, hobi, gadget, langganan aplikasi, yang kalau dikumpulkan ternyata menggerus budget cukup banyak, apalagi kalau separuhnya cuma dipakai sebentar lalu ditinggal begitu minatmu beralih ke hal lain. Kamu juga jarang benar-benar mengecek total pengeluaran kecil-kecil ini secara keseluruhan, karena masing-masing terasa remeh saat dibeli satu per satu. *PR: review langganan/hobi yang jarang dipakai tiap 3 bulan, hentikan yang sudah tidak relevan.*",
        "kesehatan": "Pikiranmu jarang berhenti bergerak dari satu topik ke topik lain, yang bagus buat kreativitas tapi melelahkan buat sistem sarafmu kalau terus-menerus tanpa jeda. Kamu juga cenderung susah tidur nyenyak karena kepala masih sibuk memikirkan banyak hal saat seharusnya sudah waktunya istirahat. *PR: sisihkan 10 menit tiap malam buat journaling atau duduk diam tanpa gadget, biar pikiran benar-benar istirahat.*",
    },
}
