"""Konten Zodiak — Leo."""

LEO_CONTENT = {
    "tagline": "☉ Matahari di Leo",
    "chip": "ZODIAK",
    "title": "Leo — Sang Pemimpin yang Hangat",
    "p1_label": "Siapa Kamu",
    "p1": "Kamu lahir saat matahari berada di rasi Leo, dan hal itu terlihat jelas dari cara orang-orang merespons kehadiranmu. Ada kehangatan alami dalam dirimu yang membuat orang di sekitarmu merasa lebih bersemangat begitu kamu masuk ke dalam ruangan. Kamu juga bukan tipe yang suka menunggu arahan; begitu sebuah ide muncul, kamu biasanya sudah lebih dulu bergerak. Kehadiranmu cenderung membawa energi positif ke mana pun kamu pergi, dan orang lain sering merasa lebih percaya diri hanya karena berada di dekatmu. Dalam lingkungan kerja, kamu cocok mengisi peran yang membutuhkan sosok yang bisa memotivasi tim dan mengarahkan mereka menuju tujuan bersama. Dalam pertemanan, kamu sering jadi pusat perhatian, bukan karena mencari-cari, tapi karena caramu bersikap memang menarik perhatian orang secara alami.",
    "p2_label": "Kekuatan & yang Perlu Dijaga",
    "p2": "Kepemimpinan memang terasa seperti bagian alami dari dirimu. Kamu mampu membuat orang lain percaya pada arah yang kamu tunjukkan, bahkan sebelum kamu sendiri sepenuhnya yakin. Namun semangat besar itu terkadang membuatmu lupa untuk mendengarkan lebih dulu sebelum mengambil keputusan, padahal orang-orang di sekitarmu juga ingin didengar, bukan hanya diarahkan. Kebutuhanmu untuk selalu tampil percaya diri ini kadang membuat kamu sulit mengakui kesalahan di depan orang lain, meski di dalam hati kamu sudah menyadarinya. Orang lain juga bisa merasa terbayangi olehmu, terutama saat kamu terlalu mendominasi percakapan atau pengambilan keputusan dalam kelompok.",
    "quote": "Kepemimpinan yang paling kuat adalah yang tahu kapan harus diam dan mendengarkan.",
    "p3_label": "PR Kecil Buat Kamu",
    "p3": 'Coba sekali saja menahan diri untuk tidak langsung memberi solusi ketika ada teman yang bercerita tentang masalahnya. Dengarkan saja sampai selesai. Kamu mungkin akan terkejut, karena terkadang orang hanya butuh didengar, bukan diarahkan, dan hal kecil ini justru akan membuat mereka semakin percaya padamu sebagai sosok pemimpin. Latih juga dirimu untuk sesekali bertanya "menurutmu bagaimana?" sebelum menyampaikan pendapatmu sendiri, supaya orang lain merasa dilibatkan, bukan hanya diarahkan.',
    "domains": {
        "karir": "Panggung adalah tempatmu bersinar, presentasi di depan klien, memimpin proyek, atau posisi yang hasil kerjanya langsung terlihat dan diakui banyak orang. Namun kesabaranmu diuji saat harus menjalani proses yang lambat atau kerja di balik layar tanpa apresiasi langsung, dan kamu bisa kehilangan motivasi kalau merasa usahamu tidak diperhatikan. Kamu juga cenderung ingin selalu jadi yang paling menonjol dalam tim, sampai kadang lupa memberi ruang bagi rekan lain untuk bersinar juga. *PR: sekali sebulan, ambil satu tugas yang hasilnya baru kelihatan lama, latih kesabaran menjalani prosesnya.*",
        "asmara": "Kamu mencintai dengan totalitas dan setia, tidak setengah-setengah kalau sudah berkomitmen, dan pasanganmu tahu betul kamu akan memperjuangkan hubungan dengan sepenuh hati. Tapi kamu juga butuh diakui secara terbuka, dan kalau merasa itu tidak datang, kamu bisa jadi posesif atau menuntut lebih dari kapasitas pasangan untuk terus-menerus memujimu. Kebutuhan akan pengakuan ini bisa membuat hubungan terasa berat sebelah, seolah semuanya harus berpusat padamu. *PR: sebelum menuntut perhatian, tanya dulu apa yang sedang dia butuhkan saat itu.*",
        "keuangan": "Kamu cenderung royal, terutama untuk hal yang menunjang citra diri, penampilan, pengalaman, hadiah untuk orang tersayang, karena bagimu tampil maksimal itu penting. Bisa jadi jebakan kalau tidak diimbangi kebiasaan menabung, terutama kalau kamu sering membeli sesuatu demi menjaga gengsi di depan orang lain, bukan karena benar-benar butuh. *PR: sisihkan minimal 10% penghasilan otomatis sebelum uang itu sempat kamu pegang.*",
        "kesehatan": 'Energimu besar tapi gampang habis kalau terus dipaksa tanpa jeda, kamu tipe yang baru berhenti setelah benar-benar kehabisan tenaga, karena tidak suka merasa "kalah" oleh rasa lelah. Bagian jantung dan punggung cenderung jadi titik lemahmu kalau kamu terus memaksakan diri tampil prima tanpa istirahat yang cukup. *PR: jadwalkan satu hari penuh tanpa agenda setiap minggu, dan benar-benar patuhi jadwal itu.*',
    },
}
