"""Konten Zodiak — Libra."""

LIBRA_CONTENT = {
    "tagline": "☉ Matahari di Libra",
    "chip": "ZODIAK",
    "title": "Libra — Penjaga Keseimbangan",
    "p1_label": "Siapa Kamu",
    "p1": "Kamu lahir saat matahari berada di rasi Libra, rasi yang dilambangkan dengan timbangan, dan itu sangat terasa dari caramu memandang keadilan serta keseimbangan dalam hidup. Kamu cenderung mempertimbangkan banyak sudut pandang sebelum mengambil keputusan, dan selalu berusaha menciptakan suasana yang harmonis di sekitarmu. Estetika dan keindahan juga terasa penting bagimu, baik dalam penampilan maupun cara kamu menata hidup. Kamu biasanya jadi sosok yang dicari saat ada perselisihan, karena kemampuanmu melihat dari berbagai sisi membuat pihak-pihak yang berkonflik merasa didengarkan secara adil. Dalam lingkungan kerja, kamu cocok mengisi peran yang membutuhkan diplomasi dan kemampuan menjaga hubungan baik antar berbagai pihak. Dalam kehidupan pribadi, kamu senang menciptakan lingkungan yang indah dan nyaman, baik untuk dirimu sendiri maupun untuk orang-orang yang kamu sayangi.",
    "p2_label": "Kekuatan & yang Perlu Dijaga",
    "p2": "Kemampuanmu melihat dari berbagai sisi membuatmu jadi penengah yang baik ketika ada konflik di sekitarmu. Orang-orang senang berdiskusi denganmu karena kamu jarang memihak secara buta. Namun kebiasaan mempertimbangkan terlalu banyak hal ini kadang membuatmu sulit mengambil keputusan sendiri, sampai akhirnya keinginanmu sendiri tertunda demi menjaga keharmonisan dengan orang lain. Kecenderungan untuk selalu mencari jalan tengah ini bisa membuatmu terjebak dalam ketidakpastian yang berkepanjangan, terutama saat situasi sebenarnya membutuhkan keputusan yang tegas dan cepat. Kamu juga bisa kehilangan jati diri sendiri karena terlalu sering menyesuaikan diri dengan keinginan orang lain.",
    "quote": "Keseimbangan yang sesungguhnya juga mencakup memberi ruang bagi keinginanmu sendiri, bukan hanya orang lain.",
    "p3_label": "PR Kecil Buat Kamu",
    "p3": "Ketika dihadapkan pada satu pilihan kecil, coba ambil keputusan sendiri tanpa bertanya pendapat orang lain terlebih dulu, lalu perhatikan bagaimana rasanya mempercayai penilaianmu sendiri. Kamu bisa mulai dari keputusan yang risikonya kecil, seperti memilih film yang akan ditonton atau tempat yang akan dikunjungi, sebelum melangkah ke keputusan yang lebih besar dan berdampak jangka panjang.",
    "domains": {
        "karir": "Kamu unggul di peran diplomasi dan menjaga hubungan antar pihak, negosiasi, kerja sama lintas tim, klien, karena kamu jago melihat kepentingan semua sisi sekaligus. Tapi kamu bisa lambat ambil keputusan sendiri, sering menunggu persetujuan orang lain dulu sebelum benar-benar yakin melangkah, sampai kesempatan yang seharusnya bisa kamu ambil justru diambil orang lain lebih dulu. *PR: sekali dalam seminggu, ambil satu keputusan kerja sendiri tanpa polling pendapat tim dulu.*",
        "asmara": "Kamu romantis dan mencari hubungan yang seimbang, selalu berusaha memastikan kedua belah pihak merasa adil diperlakukan. Tapi takut konflik bikin kamu menunda ngomongin masalah yang sebenarnya sudah lama mengganjal, sampai akhirnya menumpuk jadi kekecewaan yang lebih besar dari yang seharusnya. Pasangan mungkin tidak pernah tahu ada yang salah sampai kamu benar-benar meledak. *PR: coba sampaikan satu ketidaknyamanan kecil langsung saat itu terjadi, jangan ditimbun.*",
        "keuangan": "Kamu suka barang dan pengalaman yang estetik, yang kalau tidak dikontrol bisa menggerus budget demi tampilan atau suasana yang indah, karena bagimu keindahan visual punya nilai tersendiri yang sulit diabaikan. *PR: sebelum beli barang dekoratif, tanya apakah ini kebutuhan atau cuma pengen terlihat bagus.*",
        "kesehatan": "Kebiasaan menimbang-nimbang terlalu lama dan memendam konflik bisa memicu stres kronis tanpa kamu sadari sumbernya, karena kamu terus memikirkan berbagai kemungkinan tanpa pernah benar-benar melepaskannya. Area ginjal dan punggung bawah cenderung jadi titik lemah kalau ketegangan ini dibiarkan menumpuk lama. *PR: coba olahraga yang menstabilkan seperti yoga atau jalan santai rutin, bukan cuma pas capek pikiran.*",
    },
}
