"""Konten Zodiak — Sagittarius."""

SAGITTARIUS_CONTENT = {
    "tagline": "☉ Matahari di Sagittarius",
    "chip": "ZODIAK",
    "title": "Sagittarius — Sang Penjelajah yang Bebas",
    "p1_label": "Siapa Kamu",
    "p1": "Kamu lahir saat matahari berada di rasi Sagittarius, rasi yang identik dengan semangat menjelajah dan haus akan pengalaman baru. Kamu tidak suka merasa terkurung dalam rutinitas yang itu-itu saja, dan selalu tertarik pada hal-hal yang memperluas pandanganmu tentang dunia. Kejujuranmu yang blak-blakan membuat orang lain tahu persis apa yang kamu pikirkan, tanpa harus menebak-nebak. Kamu punya rasa optimisme yang cenderung menular, membuat orang-orang di sekitarmu ikut merasa lebih ringan menghadapi masalah mereka sendiri. Dalam pekerjaan, kamu cocok mengisi peran yang memberi ruang gerak dan variasi, karena kamu cepat merasa terkekang di lingkungan yang terlalu kaku atau monoton. Dalam pertemanan, kamu adalah tipe orang yang mengajak orang lain melihat dunia dari sudut pandang yang lebih luas dan penuh kemungkinan.",
    "p2_label": "Kekuatan & yang Perlu Dijaga",
    "p2": "Optimisme dan rasa ingin tahumu terhadap dunia membuat orang-orang di sekitarmu ikut terinspirasi untuk berani mencoba hal baru. Kamu juga jarang terjebak dalam masalah kecil karena selalu bisa melihat gambaran yang lebih besar. Sayangnya, kejujuranmu yang terlalu terus terang kadang menyakiti perasaan orang lain tanpa kamu sadari, dan keinginan bebasmu kadang membuatmu sulit berkomitmen dalam jangka panjang. Kebutuhanmu untuk selalu punya ruang bebas ini bisa membuat orang-orang terdekatmu merasa tidak yakin seberapa jauh mereka bisa mengandalkanmu, terutama dalam hubungan yang menuntut kestabilan jangka panjang.",
    "quote": "Kebebasan akan terasa lebih indah kalau kamu juga memikirkan perasaan orang yang kamu ajak bicara.",
    "p3_label": "PR Kecil Buat Kamu",
    "p3": "Sebelum menyampaikan pendapat yang cukup blak-blakan, coba jeda sebentar dan pikirkan bagaimana perasaan orang yang mendengarnya, tanpa harus mengubah kejujuranmu. Kamu juga bisa melatih diri untuk menepati satu komitmen kecil secara konsisten, sebagai cara membuktikan bahwa kebebasan yang kamu junjung tinggi tetap bisa berjalan beriringan dengan tanggung jawab.",
    "domains": {
        "karir": "Kamu cocok kerja yang variatif atau melibatkan eksplorasi dan perjalanan, dan cepat gerah di lingkungan kantor yang kaku dan monoton, merasa terkurung kalau harus duduk di meja yang sama setiap hari mengerjakan hal yang itu-itu saja. *PR: kalau terjebak rutinitas kaku, cari cara kecil menambah variasi ke tugas sehari-hari, alih-alih langsung resign.*",
        "asmara": "Kamu butuh ruang bebas dalam hubungan dan takut merasa dikekang, yang kadang bikin pasangan ragu seberapa jauh mereka bisa mengandalkanmu untuk komitmen jangka panjang. Kejujuranmu yang blak-blakan soal kebutuhan ini sebenarnya bagus, tapi kalau tidak diimbangi kepastian, pasangan bisa merasa hubungan kalian tidak punya arah yang jelas. *PR: coba komit ke satu hal kecil dan tepati konsisten, buktikan kebebasan tetap bisa jalan bareng tanggung jawab.*",
        "keuangan": 'Kamu royal untuk pengalaman, traveling, hobi baru, hal-hal yang memperluas pandangan, dibanding barang, karena bagimu pengalaman jauh lebih berharga dari kepemilikan. Tapi kurang planning jangka panjang seperti dana darurat, karena kamu lebih fokus pada kesempatan yang ada sekarang daripada kemungkinan yang belum terjadi. *PR: sisihkan satu pos khusus dana darurat sebelum uangnya "terpakai" buat pengalaman baru.*',
        "kesehatan": "Kamu aktif dan suka olahraga luar ruang, tubuhmu terasa paling hidup saat sedang bergerak dan menjelajah. Tapi rasa percaya diri berlebih bisa bikin kamu kurang hati-hati dan rawan cedera, atau malas checkup rutin karena merasa selalu fit dan tidak butuh diperiksa. Area pinggul dan paha cenderung jadi titik lemah kalau kamu terlalu memaksakan aktivitas fisik. *PR: jadwalkan medical checkup rutin walau merasa baik-baik saja.*",
    },
}
