"""Konten Zodiak — Scorpio."""

SCORPIO_CONTENT = {
    "tagline": "☉ Matahari di Scorpio",
    "chip": "ZODIAK",
    "title": "Scorpio — Sosok Misterius yang Mendalam",
    "p1_label": "Siapa Kamu",
    "p1": "Matahari berada di rasi Scorpio saat kamu lahir, memberimu kedalaman emosi dan intuisi yang tajam. Kamu jarang puas dengan hal-hal yang terlihat di permukaan saja, dan selalu ingin memahami apa yang sebenarnya terjadi di balik sesuatu. Ketika kamu benar-benar percaya pada seseorang, kesetiaanmu terasa sangat kuat, meskipun kamu tidak mudah membiarkan orang lain masuk terlalu dalam ke dunia pribadimu. Kamu punya kemampuan membaca situasi dan orang lain jauh lebih dalam dari kebanyakan orang, sering kali menangkap hal-hal yang tersembunyi di balik kata-kata atau sikap seseorang. Dalam pekerjaan, ketajaman fokus dan daya tahanmu membuatmu unggul menyelesaikan proyek yang rumit atau membutuhkan riset mendalam. Dalam hubungan, sekali kamu memutuskan untuk percaya pada seseorang, kesetiaanmu jarang goyah, bahkan di saat-saat sulit sekalipun.",
    "p2_label": "Kekuatan & yang Perlu Dijaga",
    "p2": "Ketajaman intuisi dan fokusmu membuatmu bisa menyelesaikan hal-hal yang orang lain anggap rumit atau menakutkan. Kamu juga setia dan penuh perhatian pada orang-orang yang sudah mendapat kepercayaanmu. Namun kecenderungan untuk menutup diri dan curiga secara berlebihan kadang membuat orang-orang di sekitarmu merasa sulit benar-benar dekat denganmu, meski niat mereka baik. Kebutuhanmu untuk selalu mengontrol informasi tentang dirimu sendiri ini bisa membuat hubungan terasa berat sebelah, karena kamu tahu banyak tentang orang lain, tapi orang lain tidak selalu tahu banyak tentangmu. Kamu juga bisa menyimpan kekecewaan atau kemarahan lebih lama dari yang seharusnya, sampai hal itu memengaruhi cara pandangmu terhadap seseorang secara keseluruhan.",
    "quote": "Kedalaman perasaanmu adalah kekuatan, tapi kepercayaan juga butuh ruang untuk tumbuh.",
    "p3_label": "PR Kecil Buat Kamu",
    "p3": "Coba bagikan satu hal yang biasanya kamu simpan sendiri kepada orang yang kamu percaya, sekecil apa pun itu, dan lihat bagaimana keterbukaan itu bisa mempererat hubungan kalian. Latih juga dirimu untuk melepaskan satu kekecewaan lama secara sadar, dengan mengingatkan diri sendiri bahwa memegang kemarahan terlalu lama hanya akan membebani dirimu sendiri, bukan orang yang membuatmu kecewa.",
    "domains": {
        "karir": "Fokus dan daya tahanmu bikin kamu unggul di proyek rumit yang butuh riset mendalam atau kerja krisis, jenis pekerjaan yang membuat banyak orang lain menyerah sebelum benar-benar memahami masalahnya. Tapi kamu susah delegasi atau percaya rekan kerja pegang bagian penting, karena merasa hanya kamu yang benar-benar bisa mengerjakannya dengan standar yang kamu inginkan. Ini bisa membuatmu kelebihan beban kerja tanpa disadari orang lain di sekitarmu. *PR: coba delegasikan satu tugas kecil ke rekan kerja, biar terbiasa melepas kontrol sedikit demi sedikit.*",
        "asmara": "Kesetiaanmu kuat begitu percaya pada seseorang, dan kamu akan memperjuangkan hubungan itu dengan intensitas yang jarang dimiliki orang lain. Tapi kecemburuan dan kebutuhan mengontrol informasi soal dirimu bisa bikin pasangan merasa hubungan berat sebelah, karena kamu tahu banyak tentang mereka tapi jarang membuka diri secara setara. *PR: coba ceritakan satu hal personal yang biasa kamu tutup rapat, ke pasangan yang sudah lama kamu percaya.*",
        "keuangan": "Kamu diam-diam sangat perhitungan dan strategis soal uang, punya rencana jangka panjang yang jarang kamu bagikan ke orang lain. Tapi juga bisa ambil risiko besar seperti investasi agresif tanpa cerita ke orang terdekat, karena kamu lebih nyaman mengambil keputusan besar sendirian daripada mendengar pendapat yang berbeda. *PR: sebelum ambil keputusan finansial besar sendirian, diskusikan dulu dengan satu orang yang kamu percaya.*",
        "kesehatan": "Kamu cenderung memendam stres secara internal, yang lama-lama bisa termanifestasi jadi ketegangan fisik atau gangguan tidur, karena kamu jarang menunjukkan tanda-tanda sedang kewalahan ke orang lain. Area reproduksi dan sistem eliminasi cenderung jadi titik lemah kalau emosi yang terpendam dibiarkan menumpuk terlalu lama. *PR: cari satu outlet rutin buat melepas emosi, olahraga intens, journaling, atau curhat ke orang terpercaya.*",
    },
}
