"""Konten Zodiak — Taurus."""

TAURUS_CONTENT = {
    "tagline": "☉ Matahari di Taurus",
    "chip": "ZODIAK",
    "title": "Taurus — Sosok Tenang yang Setia",
    "p1_label": "Siapa Kamu",
    "p1": "Matahari yang berada di rasi Taurus saat kamu lahir memberimu fondasi yang tenang dan stabil. Kamu tidak mudah terpancing untuk buru-buru mengambil keputusan, dan lebih memilih memastikan segalanya benar-benar matang dulu sebelum melangkah. Kesetiaanmu pada orang, kebiasaan, dan hal-hal yang sudah terbukti baik membuatmu jadi sosok yang bisa diandalkan dalam jangka panjang. Kamu juga cenderung menikmati kenyamanan fisik, seperti makanan enak, suasana rumah yang nyaman, atau rutinitas yang sudah kamu kenal baik, karena bagimu hal-hal itu memberi rasa aman yang sulit digantikan hal lain. Dalam pekerjaan, ketekunanmu membuatmu unggul di posisi yang butuh kestabilan dan hasil yang bertahan lama, bukan sekadar tren sesaat. Orang-orang terdekatmu tahu bahwa hubungan denganmu jarang berubah drastis; begitu kamu berkomitmen, kamu benar-benar menjaganya.",
    "p2_label": "Kekuatan & yang Perlu Dijaga",
    "p2": "Ketekunan dan kesabaranmu membuat apa pun yang kamu kerjakan cenderung bertahan lama dan kokoh, bukan sekadar tren sesaat. Orang-orang merasa nyaman berada di dekatmu karena kamu jarang berubah pikiran tiba-tiba. Sayangnya, kenyamanan pada rutinitas itu kadang membuatmu enggan mencoba hal baru, bahkan ketika perubahan itu sebenarnya bisa membawa hal yang lebih baik untukmu. Ketakutan terhadap ketidakpastian ini bisa membuatmu menolak peluang bagus hanya karena terasa asing atau belum teruji. Kamu juga bisa terlalu keras kepala mempertahankan cara lama, bahkan saat bukti di depan mata menunjukkan bahwa cara itu sudah tidak lagi relevan.",
    "quote": "Stabilitas itu berharga, tapi sesekali membiarkan diri berubah juga bagian dari tumbuh.",
    "p3_label": "PR Kecil Buat Kamu",
    "p3": "Coba lakukan satu hal kecil yang berbeda dari kebiasaanmu, sesuatu yang sebenarnya sudah lama ingin kamu coba tapi selalu ditunda. Tidak perlu besar, cukup untuk membuktikan pada dirimu sendiri bahwa perubahan kecil itu aman. Kamu bisa mulai dari hal sepele seperti mencoba rute baru menuju tempat kerja, atau memesan menu yang belum pernah kamu coba. Perhatikan perasaanmu setelahnya, dan gunakan pengalaman itu sebagai bukti kecil bahwa keluar dari rutinitas tidak selalu berarti kehilangan rasa aman.",
    "domains": {
        "karir": "Kamu unggul di posisi yang butuh konsistensi dan hasil tahan lama, bukan proyek yang berubah arah tiap minggu, dan atasan biasanya menaruh kepercayaan besar padamu untuk hal-hal yang butuh ketekunan bertahun-tahun. Sisi kerasnya, kamu bisa lambat beradaptasi kalau perusahaan tiba-tiba ganti sistem kerja atau arah bisnis, dan perubahan mendadak itu bisa terasa seperti ancaman, bukan sekadar penyesuaian biasa. Kamu juga cenderung menunda mengajukan diri untuk peran baru yang sebenarnya kamu sanggup, karena lebih nyaman di posisi yang sudah kamu kuasai. *PR: coba anggap perubahan sebagai versi baru dari stabilitas, bukan ancaman terhadapnya.*",
        "asmara": "Kesetiaanmu jarang goyah begitu berkomitmen, dan pasanganmu merasa aman karenanya, karena kamu bukan tipe yang gampang tergoda pindah hati begitu keadaan sedikit sulit. Tapi kamu bisa terlalu lama bertahan di hubungan yang sebenarnya sudah tidak sehat, cuma karena benci perubahan dan merasa lebih aman dengan yang sudah dikenal, meski itu berarti mengorbankan kebahagiaanmu sendiri. Kamu juga bisa keras kepala soal cara menunjukkan cinta, padahal pasangan mungkin butuh bentuk perhatian yang sedikit berbeda dari biasanya. *PR: sesekali tanya diri sendiri, ini bertahan karena cinta atau karena takut berubah?*",
        "keuangan": 'Kamu cukup baik menabung, tapi juga suka memanjakan diri dengan hal-hal yang terasa nyaman, makanan enak, barang berkualitas, pengalaman menyenangkan, karena bagimu kenyamanan fisik adalah investasi yang sama pentingnya dengan uang di rekening. Kalau tidak dijaga, pengeluaran "kenyamanan" ini bisa menggerus tabungan pelan-pelan tanpa kamu sadari, karena masing-masing pembelian terasa kecil dan wajar. Kamu juga cenderung enggan menjual atau melepas aset lama meski sudah tidak terlalu berguna, karena merasa sayang atau terikat secara emosional. *PR: catat khusus pos "kenyamanan diri" tiap bulan biar kelihatan totalnya.*',
        "kesehatan": "Kamu suka menikmati makanan enak dan gaya hidup santai, yang enak tapi bisa berujung kurang gerak kalau dibiarkan terus, apalagi kalau rutinitas harianmu memang tidak banyak menuntut aktivitas fisik. Area leher dan tenggorokan cenderung jadi titik lemahmu, dan kamu mungkin baru sadar ada yang salah setelah masalahnya cukup mengganggu, karena kamu jarang proaktif memeriksakan diri selagi masih merasa baik-baik saja. *PR: pasang jadwal jalan kaki/olahraga ringan rutin, bukan cuma pas mood.*",
    },
}
