"""Konten Zodiak — Virgo."""

VIRGO_CONTENT = {
    "tagline": "☉ Matahari di Virgo",
    "chip": "ZODIAK",
    "title": "Virgo — Perfeksionis yang Teliti",
    "p1_label": "Siapa Kamu",
    "p1": "Matahari yang berada di rasi Virgo saat kamu lahir memberimu ketelitian yang jarang dimiliki banyak orang. Kamu memperhatikan detail-detail kecil yang sering terlewat oleh orang lain, dan hal itu membuat pekerjaanmu biasanya rapi serta minim kesalahan. Kamu juga punya standar tinggi terhadap diri sendiri, dan selalu berusaha memberikan yang terbaik dalam segala hal yang kamu kerjakan. Kecenderungan untuk menganalisis ini juga muncul dalam caramu memandang berbagai situasi, kamu jarang menerima sesuatu begitu saja tanpa memikirkan bagaimana hal itu bisa diperbaiki atau disempurnakan. Dalam pekerjaan, ketelitianmu membuatmu unggul di peran yang membutuhkan akurasi tinggi, seperti mengelola data, menyusun rencana yang rinci, atau memastikan kualitas sebuah hasil kerja. Orang-orang di sekitarmu tahu bahwa kalau ada sesuatu yang kamu periksa, kemungkinan besar hasilnya akan lebih rapi dari sebelumnya.",
    "p2_label": "Kekuatan & yang Perlu Dijaga",
    "p2": "Ketelitian dan tanggung jawabmu membuat orang lain percaya menyerahkan pekerjaan penting kepadamu, karena tahu kamu akan mengurusnya dengan serius. Kamu juga jago melihat celah perbaikan yang orang lain lewatkan. Sayangnya, standar tinggi itu kadang berbalik menjadi kritik yang terlalu keras terhadap dirimu sendiri, sampai lupa mengapresiasi hal-hal yang sudah kamu capai dengan baik. Kebiasaan ini juga bisa membuatmu terlalu fokus pada kekurangan kecil, sampai kehilangan gambaran besar tentang seberapa jauh sebenarnya kamu sudah maju. Orang lain di sekitarmu mungkin merasa sungkan menunjukkan hasil kerja mereka kepadamu, karena khawatir dinilai terlalu detail.",
    "quote": "Kesempurnaan itu indah untuk dikejar, tapi jangan sampai membuatmu lupa menghargai kemajuan yang sudah ada.",
    "p3_label": "PR Kecil Buat Kamu",
    "p3": "Sebelum tidur, coba tuliskan satu hal kecil yang sudah kamu kerjakan dengan baik hari itu, tanpa langsung memikirkan apa yang masih kurang darinya. Lakukan ini secara konsisten selama beberapa minggu, dan perhatikan bagaimana kebiasaan ini perlahan membantumu melihat kemajuanmu sendiri dengan lebih adil, bukan hanya berfokus pada apa yang belum sempurna.",
    "domains": {
        "karir": 'Ketelitianmu jadi aset besar di pekerjaan yang butuh akurasi tinggi, QA, analisis data, penyusunan rencana rinci, dan atasan biasanya menaruh kepercayaan besar padamu untuk hal-hal yang tidak boleh salah sedikit pun. Tapi standar tinggi ke diri sendiri bisa berujung burnout kalau tidak direm, karena kamu jarang merasa hasil kerjamu sudah cukup baik meski orang lain sudah memujinya. Kamu juga bisa terlalu lama memeriksa ulang sesuatu yang sebenarnya sudah selesai, sampai kehilangan waktu untuk mengerjakan hal lain yang sama pentingnya. *PR: tetapkan batas "cukup baik" untuk tugas kecil, simpan energi maksimal buat yang benar-benar penting.*',
        "asmara": 'Kamu menunjukkan cinta lewat tindakan praktis, bantuin beresin masalah, memperhatikan detail kebutuhan pasangan yang bahkan mereka sendiri belum sadari. Sayangnya ini kadang ditangkap sebagai "banyak protes" atau terlalu mengoreksi, karena caramu peduli sering dibungkus dalam bentuk kritik atau saran perbaikan. Pasangan mungkin merasa tidak pernah cukup baik di matamu, padahal maksudmu sebenarnya ingin membantu supaya semuanya berjalan lebih baik. *PR: sesekali puji dulu sebelum kasih masukan perbaikan.*',
        "keuangan": 'Kamu rapi mencatat pengeluaran dan cenderung hemat, tahu persis ke mana uangmu pergi setiap bulan, dan jarang terkejut dengan tagihan yang tidak terduga. Tapi bisa terlalu pelit ke diri sendiri sampai jarang menikmati hasil kerja keras, merasa bersalah setiap kali mengeluarkan uang untuk sesuatu yang sifatnya murni kesenangan. *PR: alokasikan budget kecil khusus "untuk senang-senang" tiap bulan, tanpa rasa bersalah.*',
        "kesehatan": "Kecenderungan overthinking dan mengkritik diri sendiri sering muncul sebagai gejala fisik, sakit kepala, perut tegang, susah rileks, karena pikiranmu jarang benar-benar berhenti mengevaluasi. Sistem pencernaanmu cenderung jadi titik lemah kalau kamu terus-menerus menyimpan kecemasan soal kesempurnaan. *PR: latih self-compassion sederhana, bicara ke diri sendiri seperti kamu bicara ke sahabat yang sedang berjuang.*",
    },
}
